import {z} from 'zod';
import {getAddress,isAddress,verifyMessage} from 'viem';
import {PlatformError} from './service.js';
import {creatorSecretHash} from './submissions.js';
import {hash} from './telemetry.js';
import {canonical} from './x402.js';
const key=z.string().regex(/^[A-Za-z0-9_-]{32,128}$/),revision=z.number().int().min(1).max(2147483647);
export const walletClaimSchema=z.strictObject({request_id:key,expected_revision:z.number().int().min(0).max(2147483646),network:z.literal('eip155:8453'),address:z.string().refine(a=>isAddress(a,{strict:true})&&!/^0x0{40}$/i.test(a))});
export const walletChallengeSchema=z.strictObject({request_id:key,claim_revision:revision});
export const walletVerifySchema=z.strictObject({challenge_id:z.uuid(),signature:z.string().regex(/^0x[0-9a-fA-F]{130}$/)});
export const walletHistorySchema=z.strictObject({limit:z.coerce.number().int().min(1).max(20).default(10),cursor:z.string().regex(/^[A-Za-z0-9_-]{1,256}$/).optional()});
const fail=(status,code,message)=>new PlatformError(status,code,message);
const conflict=()=>fail(409,'wallet_conflict','Read the current wallet revision; request IDs bind the original body.');
function parse(schema,body){const r=schema.safeParse(body);if(!r.success)throw fail(400,'invalid_wallet_request','Use the published wallet schema.');return r.data;}
async function creator(db,capability){const c=await db.prepare('SELECT creator_id FROM platform_creators WHERE capability_hash=?').bind(await creatorSecretHash(capability)).first();if(!c)throw fail(403,'creator_capability_invalid','A matching existing creator capability is required.');return c.creator_id;}
const current=(db,c)=>db.prepare('SELECT * FROM platform_creator_wallet_claims WHERE creator_id=? ORDER BY revision DESC LIMIT 1').bind(c).first();
async function view(db,r){if(!r)return null;const proof=await db.prepare('SELECT created_at FROM platform_creator_wallet_proofs WHERE claim_id=? ORDER BY created_at LIMIT 1').bind(r.claim_id).first(),approval=await db.prepare('SELECT created_at FROM platform_creator_wallet_approvals WHERE claim_id=?').bind(r.claim_id).first();return {claim_id:r.claim_id,revision:r.revision,network:r.network,address:r.address,created_at:r.created_at,ownership_status:proof?'eoa_signature_verified':'unverified',ownership_proof:proof?{verified_at:proof.created_at,method:'eoa_erc191',erc1271_supported:false}:null,owner_approval:approval?{status:'approved',approved_at:approval.created_at}:{status:'pending'},payment_effect:'none'};}
async function insert(db,sql,args,reload,requestHash){try{await db.prepare(sql).bind(...args).run();}catch(e){const r=await reload();if(r){if(r.request_hash!==requestHash)throw conflict();return r;}if(/wallet_budget_exhausted/.test(String(e)))throw fail(429,'wallet_budget_exhausted','Wallet write budget exhausted; retry another day.');if(/wallet_.*conflict|wallet_has_reserved_payout|UNIQUE constraint/.test(String(e)))throw conflict();throw e;}const r=await reload();if(!r||r.request_hash!==requestHash)throw conflict();return r;}
export async function claimWallet({db,body,capability,now=()=>new Date()}){const c=await creator(db,capability),d=parse(walletClaimSchema,body);d.address=getAddress(d.address);const kh=await hash(d.request_id),rh=await hash(canonical(d)),reload=()=>db.prepare('SELECT * FROM platform_creator_wallet_claims WHERE creator_id=? AND request_key_hash=?').bind(c,kh).first(),prior=await reload();if(prior){if(prior.request_hash!==rh)throw conflict();return view(db,prior);}const r=await insert(db,'INSERT INTO platform_creator_wallet_claims VALUES(?,?,?,?,?,?,?,?,?)',[crypto.randomUUID(),c,d.expected_revision+1,d.expected_revision,d.network,d.address,kh,rh,now().toISOString()],reload,rh);return view(db,r);}
export async function getWallet({db,capability,params={}}){const c=await creator(db,capability),d=parse(walletHistorySchema,params),head=await current(db,c);let before=2147483648;if(d.cursor){try{const cursor=JSON.parse(atob(d.cursor.replaceAll('-','+').replaceAll('_','/')));if(cursor.scope!==await hash(c)||!Number.isInteger(cursor.before)||cursor.before<1||cursor.before>2147483648||Object.keys(cursor).length!==2)throw Error();before=cursor.before;}catch{throw fail(400,'invalid_cursor','Use the returned private wallet cursor.');}}const rows=(await db.prepare('SELECT * FROM platform_creator_wallet_claims WHERE creator_id=? AND revision<? ORDER BY revision DESC LIMIT ?').bind(c,before,d.limit+1).all()).results,page=rows.slice(0,d.limit);return {api_version:'1',wallet:await view(db,head),history:await Promise.all(page.map(r=>view(db,r))),next_cursor:rows.length>d.limit?btoa(JSON.stringify({scope:await hash(c),before:page.at(-1).revision})).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''):null};}
function domain(origin){let u;try{u=new URL(origin);}catch{throw fail(400,'invalid_wallet_origin','A configured HTTPS origin is required.');}if(u.protocol!=='https:'||u.origin!==origin)throw fail(400,'invalid_wallet_origin','Use the configured HTTPS origin.');return u.host;}
function challengeView(r){return {challenge_id:r.challenge_id,claim_revision:r.claim_revision,address:r.address,message:r.message,expires_at:r.expires_at,method:'eoa_erc191',erc1271_supported:false,payment_effect:'none'};}
export async function challengeWallet({db,body,capability,origin,now=()=>new Date()}){const c=await creator(db,capability),d=parse(walletChallengeSchema,body),host=domain(origin),kh=await hash(d.request_id),rh=await hash(canonical({...d,origin})),reload=()=>db.prepare('SELECT * FROM platform_creator_wallet_challenges WHERE creator_id=? AND request_key_hash=?').bind(c,kh).first(),prior=await reload();if(prior){if(prior.request_hash!==rh)throw conflict();return challengeView(prior);}const claim=await current(db,c);if(!claim||claim.revision!==d.claim_revision)throw conflict();const id=crypto.randomUUID(),nonce=crypto.randomUUID().replaceAll('-',''),date=now(),created=date.toISOString(),expires=new Date(date.getTime()+300000).toISOString(),message=`${host} wants you to sign in with your Ethereum account:\n${claim.address}\n\nProve ownership of an AGI payout destination. This does not authorize payment.\n\nURI: ${origin}\nVersion: 1\nChain ID: 8453\nNonce: ${nonce}\nIssued At: ${created}\nExpiration Time: ${expires}\nRequest ID: ${id}\nResources:\n- urn:agi:action:payout-destination-proof\n- urn:agi:creator:${await hash(c)}\n- urn:agi:wallet-claim:${claim.claim_id}:revision:${claim.revision}`;return challengeView(await insert(db,'INSERT INTO platform_creator_wallet_challenges VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[id,c,claim.claim_id,claim.revision,claim.address,origin,message,nonce,kh,rh,created,expires],reload,rh));}
export async function verifyWallet({db,body,capability,origin,now=()=>new Date()}){const c=await creator(db,capability),d=parse(walletVerifySchema,body);domain(origin);const h=await db.prepare('SELECT * FROM platform_creator_wallet_challenges WHERE challenge_id=? AND creator_id=?').bind(d.challenge_id,c).first();if(!h)throw fail(403,'wallet_challenge_invalid','No matching private challenge.');if(h.origin!==origin)throw conflict();const ph=await hash(canonical({challenge_id:d.challenge_id,signature:d.signature.toLowerCase(),origin})),reload=()=>db.prepare('SELECT * FROM platform_creator_wallet_proofs WHERE challenge_id=?').bind(h.challenge_id).first();let prior=await reload();if(prior){if(prior.proof_hash!==ph)throw conflict();return view(db,await db.prepare('SELECT * FROM platform_creator_wallet_claims WHERE claim_id=?').bind(h.claim_id).first());}const date=now().toISOString(),head=await current(db,c);if(date<h.created_at||date>=h.expires_at||head?.claim_id!==h.claim_id)throw conflict();let valid=false;try{valid=await verifyMessage({address:h.address,message:h.message,signature:d.signature});}catch{}if(!valid)throw fail(400,'wallet_signature_invalid','The EOA signature must match the exact destination challenge; ERC-1271 is unsupported.');try{await db.prepare('INSERT INTO platform_creator_wallet_proofs VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),c,h.claim_id,h.challenge_id,ph,date).run();}catch(e){prior=await reload();if(prior){if(prior.proof_hash!==ph)throw conflict();}else if(/wallet_budget_exhausted/.test(String(e)))throw fail(429,'wallet_budget_exhausted','Wallet write budget exhausted.');else if(/wallet_.*conflict/.test(String(e)))throw conflict();else throw e;}return view(db,head);}
// Internal owner workflow only. Caller must establish owner authorization; no public route.
export async function approveWallet({db,claimId,reviewer,requestId,now=()=>new Date()}){if(typeof reviewer!=='string'||!reviewer.trim()||reviewer.length>128||!key.safeParse(requestId).success)throw fail(400,'invalid_wallet_approval','An authenticated owner reviewer and request ID are required.');const kh=await hash(requestId),rh=await hash(canonical({claimId,reviewer})),reload=()=>db.prepare('SELECT * FROM platform_creator_wallet_approvals WHERE reviewer=? AND request_key_hash=?').bind(reviewer,kh).first();const prior=await reload();if(prior){if(prior.request_hash!==rh)throw conflict();return {approval_id:prior.approval_id,claim_id:prior.claim_id,approved_at:prior.created_at};}const r=await insert(db,'INSERT INTO platform_creator_wallet_approvals VALUES(?,?,?,?,?,?)',[crypto.randomUUID(),claimId,reviewer,kh,rh,now().toISOString()],reload,rh);return {approval_id:r.approval_id,claim_id:r.claim_id,approved_at:r.created_at};}
