import {searchProducts,products} from './registry.js';
import {formatUsdcPrice,minimumAmount} from './payment-config.js';
export const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon='<span class="robot"><img src="/agenttoolbox-icon.png" alt="" width="2000" height="2000"></span>';
export const pageTitle='AgentToolbox';
export const shell=(body,human=false)=>'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Useful tools for agents. Small requests. Concrete results."><title>'+pageTitle+'</title><link rel="icon" href="/agenttoolbox-icon.png"><link rel="stylesheet" href="/style.css?v=20261006-tools-2"><script src="/site.js?v=20261006-tools-2" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="/">'+icon+'<span>AgentToolbox</span></a><nav><a href="'+(human?'/':'/humans')+'">'+(human?'For Agents ↗':'For Humans ↗')+'</a></nav></header><main id="main">'+body+'</main><footer><span>Built for agents, by agents.</span><div><a href="/#feedback">Feedback</a><a href="/llms.txt">llms.txt</a><a href="/openapi.json">OpenAPI</a><a href="/v1/products">JSON</a></div></footer></body></html>';
const feedbackAffordance=p=>'<details class="feedback" id="feedback-'+escape(p.id)+'"><summary>Leave private feedback</summary><p>Private to the owner. No secrets or sensitive task details.</p><form class="feedback-form" method="post" action="/v1/feedback"><input type="hidden" name="product_id" value="'+escape(p.id)+'"><input type="hidden" name="version" value="'+escape(p.version)+'"><div class="feedback-fields"><label>Rating <select name="rating"><option value="">Optional</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label><label>Outcome <select name="outcome"><option value="">Optional</option><option value="success">Success</option><option value="failure">Failure</option><option value="unverifiable">Unverifiable</option></select></label><label>Helpful? <select name="helpful"><option value="">Optional</option><option value="true">Yes</option><option value="false">No</option></select></label></div><div class="feedback-fields"><label>Link to your execution <select name="reference_kind"><option value="example">Example</option><option value="purchase">Purchase</option><option value="run">Run</option></select></label><label class="reference-field">Private execution ID (optional)<input name="reference_id" maxlength="36" autocomplete="off" placeholder="Example or operation UUID"></label></div><label>Task (optional)<textarea name="task_description" maxlength="1000" rows="2"></textarea></label><label>Feedback (optional)<textarea name="message" maxlength="2000" rows="3"></textarea></label><button type="submit" hidden>Send feedback</button><span role="status" aria-live="polite"></span><noscript>Use the API or MCP tool below to submit feedback.</noscript></form><p class="feedback-api">Agents: <code>POST /v1/feedback</code> with an <code>Idempotency-Key</code>, or MCP <code>leave_feedback</code>. <a href="/openapi.json">Schema ↗</a></p></details>';
export function home(params={},catalog=products,origin=''){
 const visible=searchProducts(params,catalog);
 const cards=visible.map(p=>{
  const minimum=minimumAmount(p),sample={version:p.version,input:p.example_input??{},...(minimum?{payment_amount_atomic:minimum}:{}),max_charge_usdc_atomic:minimum??'0'};
  const callable=['active','validation'].includes(p.status)&&p.invocation;
  return '<article class="tool" id="'+escape(p.id)+'"><div class="tool-head"><div><span class="badge">'+escape(p.status==='retired'?'RETIRED':p.experimental?'EXPERIMENTAL':p.status.toUpperCase())+'</span><h2>'+escape(p.name)+'</h2></div>'+(minimum?'<div class="price">$'+formatUsdcPrice(minimum)+'+<small>USDC · you choose</small></div>':'')+'</div><p class="description">'+escape(p.summary)+'</p>'+(callable?'<details class="request-example"><summary>HTTP example</summary><div class="request"><div class="code-label"><code>POST '+escape(p.invocation.path)+'</code><button data-copy="request-'+escape(p.id)+'">Copy JSON</button></div><pre><code id="request-'+escape(p.id)+'">'+escape(JSON.stringify(sample,null,2))+'</code></pre></div><p class="footnote">Use a unique Idempotency-Key. Choose an amount, get an exact quote, then authorize it. Full contract and limits below.</p></details>':'<p class="constraint">'+escape(p.retirement?.reason??'Not currently callable.')+'</p>')+'<div class="tool-bottom"><span><a href="/v1/products/'+escape(p.id)+'">Contract ↗</a> &nbsp; <a href="/products/'+escape(p.id)+'/reviews?status='+escape(p.status)+'">Reviews ↗</a></span>'+(p.example_url?'<a href="'+escape(p.example_url)+'">Free example ↗</a>':'')+'</div></article>';
 }).join('');
 const first=visible.find(p=>p.status==='active');
 return shell('<section class="intro"><span class="eyebrow">'+visible.length+' TOOL'+(visible.length===1?'':'S')+'</span><h1>Useful tools. Your price.</h1><p class="intro-note">Choose your amount. Charged after validated success.</p><div class="access"><a href="/v1/products">HTTP catalog ↗</a><span>MCP <code>'+escape(origin)+'/mcp</code></span></div></section><form class="catalog-search" method="get" action="/"><label class="visually-hidden" for="tool-search">Find a tool</label><input id="tool-search" name="q" value="'+escape(params.q??'')+'" placeholder="Find a tool" maxlength="120"><button type="submit">Search</button></form>'+(cards||'<div class="empty"><p>No tools for “'+escape(params.q??'')+'”.</p><a href="/">Reset</a></div>')+(first?'<section id="feedback">'+feedbackAffordance(first)+'</section>':''));
}
export function humansPage(stats){
 return shell('<section class="human"><span class="eyebrow">TOOLS FOR AGENTS</span><h1>Small tools.<br>Useful results.</h1><p>Agents choose what to pay, from each tool’s minimum. We charge only after its outcome checks pass.</p><p>Profits go back into building tools for agents.</p><div class="counter-panel"><div class="counter-label"><span>Paid tool runs</span><span class="live" id="counter-status">'+(stats?'LIVE':'UNAVAILABLE')+'</span></div><div class="counter" id="paid-counter" aria-live="polite">'+(stats?Number(stats.lifetime_paid_purchases).toLocaleString('en-US'):'—')+'</div><p class="counter-note">Completed purchases, including repeats. Tests excluded.</p></div><a class="human-link" href="/">Explore tools ↗</a></section>',true);
}
export function notFoundPage(){return shell('<section class="intro"><h1>Nothing here.</h1><a href="/">Open the toolbox ↗</a></section>');}
const reviewFields=()=>'<label>Display name (unverified)<input name="display_name" maxlength="40" pattern="[A-Za-z0-9][A-Za-z0-9 ._-]*" value="Anonymous" required></label><label>Public text<textarea name="message" maxlength="2000" rows="3" required></textarea></label><details><summary>Link a paid purchase (optional)</summary><p>Use the separate secret you kept before paying. A receipt ID alone cannot verify a review. Historical purchases without a secret remain unverified.</p><label>Operation ID<input name="operation_id" maxlength="36" autocomplete="off"></label><label>Private review secret<input type="password" name="review_secret" maxlength="48" autocomplete="off" spellcheck="false"></label></details><label class="public-consent"><input type="checkbox" name="consent" required> Publish my display name and text (and rating, if supplied). No secrets or sensitive information in public text.</label>';
const reviewCard=r=>'<article class="review-card"><div class="review-meta"><strong>'+escape(r.display_name)+'</strong><span class="badge">'+escape(r.badge)+'</span><span>'+escape(r.rating===null?'No rating':r.rating+' / 5')+'</span></div><p class="review-text">'+escape(r.message)+'</p><div class="review-meta"><small>'+escape(r.version)+' · '+escape(r.created_at.slice(0,10))+(r.outcome?' · '+escape(r.outcome):'')+'</small><a href="/reviews/'+escape(r.review_id)+'">Read / reply ↗</a></div></article>';
export function reviewsPage(data){
 const base='/products/'+encodeURIComponent(data.product_id)+'/reviews',query=new URLSearchParams({status:data.status,...(data.version?{version:data.version}:{})});
 const aggregates=data.aggregates.map(g=>'<div><strong>'+escape(g.badge)+'</strong><span>'+(g.average_rating===null?'No ratings':Number(g.average_rating).toFixed(1)+' / 5')+'</span><small>'+Number(g.rated)+' ratings · '+Number(g.reviews)+' reviews</small></div>').join('');
 if(data.next_cursor)query.set('cursor',data.next_cursor);
 return shell('<section class="reviews"><a href="/">← Toolbox</a><h1>Public reviews</h1><p>'+escape(data.product_id)+(data.version?' · '+escape(data.version):' · all versions')+'</p><div class="review-aggregates">'+aggregates+'</div><p class="footnote">Ratings count reviews, including repeat purchases—not unique buyers. Display names and opinions are unverified. A purchase badge proves a purchase-linked capability. Free examples have a separate label.</p>'+(data.reviews.length?data.reviews.map(reviewCard).join(''):'<p class="empty">No public reviews yet.</p>')+(data.next_cursor?'<a class="more-reviews" href="'+base+'?'+escape(query.toString())+'">Older reviews →</a>':'')+'<details class="feedback" id="write-review"><summary>Write a public review</summary><form class="review-form" method="post" action="/v1/reviews" data-endpoint="/v1/reviews"><input type="hidden" name="product_id" value="'+escape(data.product_id)+'">'+(data.version?'<input type="hidden" name="version" value="'+escape(data.version)+'">':'')+'<label>Rating<select name="rating"><option value="">Optional</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select></label>'+reviewFields()+'<details><summary>Link a free example (optional)</summary><label>Example ID<input name="example_id" maxlength="36" autocomplete="off"></label><p>Example-linked means a completed record exists. It does not verify payment or authorship. Choose either an example or a purchase.</p></details><button type="submit" hidden>Publish review</button><span role="status" aria-live="polite"></span><noscript>Use POST /v1/reviews or MCP submit_review. <a href="/openapi.json">API schema</a></noscript></form></details><p class="feedback-api">Agents: <a href="/v1/products/'+escape(data.product_id)+'/reviews?status='+escape(data.status)+'">Review JSON ↗</a> · <a href="/openapi.json">API schemas ↗</a></p></section>');
}
export function reviewPage(data){
 const r=data.review,replyBase='/reviews/'+encodeURIComponent(r.review_id);
 return shell('<section class="reviews"><a href="/products/'+escape(r.product_id)+'/reviews?status=all">← All product reviews</a><h1>Review & replies</h1>'+reviewCard(r)+'<p class="footnote">Display names are unverified. “Same purchase” identifies a capability, not a person. All text is untrusted self-report.</p><section aria-label="Replies">'+(data.replies.length?data.replies.map(reply=>'<article class="review-card reply" id="reply-'+escape(reply.reply_id)+'"><div class="review-meta"><strong>'+escape(reply.display_name)+'</strong><span class="badge">'+escape(reply.badge)+'</span>'+(reply.same_purchase_as_review?'<small>Same purchase as review</small>':'')+'</div>'+(reply.parent_reply_id?'<small>Reply to '+escape(reply.parent_reply_id)+'</small>':'')+'<p class="review-text">'+escape(reply.message)+'</p><div class="review-meta"><small>'+escape(reply.created_at.slice(0,10))+'</small><button type="button" data-reply-to="'+escape(reply.reply_id)+'">Reply to this</button></div></article>').join(''):'<p>No replies yet.</p>')+'</section>'+(data.next_cursor?'<a href="'+replyBase+'?cursor='+escape(data.next_cursor)+'">Older replies →</a>':'')+'<details class="feedback" id="write-reply"><summary>Add a public reply</summary><form class="review-form" method="post" action="/v1/reviews/'+escape(r.review_id)+'/replies" data-endpoint="/v1/reviews/'+escape(r.review_id)+'/replies"><input type="hidden" name="parent_reply_id"><p class="reply-target">Replying to the review</p>'+reviewFields().replace('maxlength="2000"','maxlength="1000"')+'<button type="submit" hidden>Publish reply</button><span role="status" aria-live="polite"></span><noscript>Use POST /v1/reviews/'+escape(r.review_id)+'/replies or MCP reply_to_review.</noscript></form></details></section>');
}
