import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {database} from '../scripts/local-db.js';
import {createPlatform} from '../src/app.js';
import {registerReferral,REFERRAL_TERMS} from '../src/referrals.js';
import {BASE_NETWORK,BASE_USDC} from '../src/payment-config.js';
import {attachBeneficiaryPayoutApi,beneficiaryPayoutRoute,registerBeneficiaryPayoutTools,addBeneficiaryPayoutOpenApi} from '../src/beneficiary-payout-api.js';
const origin='https://payout.example.invalid',date=new Date().toISOString(),capability='atbf_'+Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64url'),other='atbf_'+Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64url'),account=privateKeyToAccount(generatePrivateKey()),uuid=()=>crypto.randomUUID();
async function setup(){const db=database(),registration=await registerReferral({db,body:{terms_version:REFERRAL_TERMS.terms_version},capability,client:'local-api-fixture'});return {db,code:registration.referral_code};}
function accrue(db,code){const operation=uuid(),transaction='0x'+operation.replaceAll('-','').padEnd(64,'a'),source='0x'+'11'.repeat(20);db.sqlite.prepare(`INSERT INTO platform_payments(operation_id,product_id,version,key_hash,fingerprint,payment_digest,network,asset,payer,nonce,amount_atomic,receiver,state,created_at,updated_at,sample_kind,is_live,referral_code,referral_terms_version,referral_share_bps) VALUES(?,'docs-pack','0.1.0',?,'fixture','fixture',?,?,?,?,?,?,'settling',?,?,'synthetic',1,?,?,100)`).run(operation,uuid(),BASE_NETWORK,BASE_USDC,source,uuid(),'10001',source,date,date,code,REFERRAL_TERMS.terms_version);const stmt=db.sqlite.prepare('INSERT INTO platform_payment_ledger VALUES(?,?,?,?,?,?,?,?,?,?,?)');for(const event of ['outcome_validated','settlement_reported'])stmt.run(uuid(),operation,'docs-pack','0.1.0',event,BASE_NETWORK,BASE_USDC,'10001',transaction,'synthetic',date);db.sqlite.prepare("UPDATE platform_payments SET state='settled' WHERE operation_id=?").run(operation);}
const post=(body,cap=capability)=>({method:'POST',headers:{'Content-Type':'application/json','X-Referral-Capability':cap},body:JSON.stringify(body)});
test('route adapter forwards only private header capabilities, query bounds and request bodies',async()=>{const calls=[],api=new Proxy({}, {get:(_,name)=>(...args)=>{calls.push({name,args});return {ok:true};}}),jsonBody=r=>r.json();const cases=[['/v1/referrals/me/payout-wallet','getReferralWallet'],['/v1/referrals/me/earnings','getReferralEarnings'],['/v1/referrals/me/payout-requests','listReferralPayoutRequests'],['/v1/referrals/me/payout-requests/'+uuid(),'getReferralPayoutRequest'],['/v1/creator-tools/creator-'+uuid()+'/payout-requests','listCreatorPayoutRequests']];for(const [path,name] of cases){const request=new Request(origin+path+'?capability=ignored&limit=2',{headers:{'X-Referral-Capability':capability,'X-Creator-Capability':'creator-private'}});assert.equal((await beneficiaryPayoutRoute({request,url:new URL(request.url),api,jsonBody})).status,200);assert.equal(calls.at(-1).name,name);assert(!calls.at(-1).args.includes('ignored'));}for(const [path,name] of [['/v1/referrals/me/payout-wallet','claimReferralWallet'],['/v1/referrals/me/payout-wallet/challenge','challengeReferralWallet'],['/v1/referrals/me/payout-wallet/verify','verifyReferralWallet'],['/v1/referrals/me/payout-requests','requestReferralPayout']]){const request=new Request(origin+path,post({request_id:'fixture'}));await beneficiaryPayoutRoute({request,url:new URL(request.url),api,jsonBody});assert.equal(calls.at(-1).name,name);assert.deepEqual(calls.at(-1).args,[{request_id:'fixture'},capability]);}const request=new Request(origin+'/v1/owner/payouts');assert.equal(await beneficiaryPayoutRoute({request,url:new URL(request.url),api,jsonBody}),null);});
test('all write API methods use the shared budget hook before database access',async()=>{let count=0;const api={};attachBeneficiaryPayoutApi(api,{db:{},origin,writeAllowed:async()=>{count++;return false;}});for(const [name,args] of [['registerReferral',[{},capability]],['claimReferralWallet',[{},capability]],['challengeReferralWallet',[{},capability]],['verifyReferralWallet',[{},capability]],['requestReferralPayout',[{},capability]],['requestCreatorPayout',['creator-'+uuid(),{},'private']]])await assert.rejects(api[name](...args),e=>e.status===429&&e.code==='rate_limited');assert.equal(count,6);});
test('MCP registrations expose strict bounded public inputs and correct read-only flags',()=>{const tools=[],api=new Proxy({},{get:(_,name)=>(...args)=>({name,args})});registerBeneficiaryPayoutTools((name,description,schema,handler,readOnly)=>tools.push({name,description,schema,handler,readOnly}),api);assert.equal(tools.length,14);assert(tools.every(t=>!t.name.includes('owner')));const body={request_id:uuid(),amount_atomic:'1',claim_revision:1,referral_capability:capability};const tool=tools.find(t=>t.name==='request_referral_payout');assert(tool.schema.safeParse(body).success);assert(!tool.schema.safeParse({...body,reviewer:'forged'}).success);assert.equal(tool.readOnly,false);assert.deepEqual(tool.handler(body),{name:'requestReferralPayout',args:[{request_id:body.request_id,amount_atomic:'1',claim_revision:1},capability]});assert(tools.filter(t=>/^(get|list)_/.test(t.name)).every(t=>t.readOnly));});
test('OpenAPI contains typed proof, earnings and permanent request link responses',()=>{const document={paths:{}},creatorHeader={name:'X-Creator-Capability',in:'header',required:true,schema:{type:'string'}},referralHeader={name:'X-Referral-Capability',in:'header',required:true,schema:{type:'string'}};addBeneficiaryPayoutOpenApi(document,creatorHeader,referralHeader);assert.equal(Object.keys(document.paths).length,8);const wallet=document.paths['/v1/referrals/me/payout-wallet'];assert.equal(wallet.post.parameters[0].name,'X-Referral-Capability');const earnings=document.paths['/v1/referrals/me/earnings'].get.responses[200].content['application/json'].schema;assert.equal(earnings.properties.share_bps.const,100);const response=document.paths['/v1/referrals/me/payout-requests/{request_id}'].get.responses[200].content['application/json'].schema;assert(response.required.includes('payout'));assert(response.properties.payout.anyOf.some(x=>x.properties?.receipt));assert(document.paths['/v1/creator-tools/{tool_id}/payout-requests'].post.requestBody.content['application/json'].schema.required.includes('claim_revision'));assert(!JSON.stringify(document).includes('/owner/'));});
test('real app referral wallet, earnings and payout requests preserve private capability and frozen amounts',async()=>{const {db,code}=await setup();const app=createPlatform({db,origin,payoutRequestsEnabled:true}),request=(path,init={})=>app(new Request(origin+path,init),'local-api-fixture');try{
 const path='/v1/referrals/me/payout-wallet',headers={'X-Referral-Capability':capability};
 assert.equal((await request(path)).status,403);assert.equal((await request(path+'?capability='+capability)).status,403);
 const claimBody={request_id:uuid(),expected_revision:0,network:BASE_NETWORK,address:account.address},claimResponse=await request(path,post(claimBody));assert.equal(claimResponse.status,200);const claim=await claimResponse.json();assert.equal(claim.ownership_status,'unverified');
 const challengeResponse=await request(path+'/challenge',post({request_id:uuid(),claim_revision:1}));assert.equal(challengeResponse.status,200);const challenge=await challengeResponse.json();assert(challenge.message.includes('\n'));assert(!challenge.message.includes('\\n'));
 const signature=await account.signMessage({message:challenge.message});const verified=await request(path+'/verify',post({challenge_id:challenge.challenge_id,signature}));assert.equal(verified.status,200);assert.equal((await verified.json()).ownership_status,'eoa_signature_verified');
 accrue(db,code);const earningsResponse=await request('/v1/referrals/me/earnings',{headers});assert.equal(earningsResponse.status,200);const earnings=await earningsResponse.json();assert.equal(earnings.accrued_atomic,'100');assert.equal(earnings.share_bps,100);assert.equal(earnings.fractional_atom_numerator,'100');assert.equal(earnings.confirmed_paid_atomic,'0');assert.equal(earnings.reserved_atomic,'0');
 const body={request_id:uuid(),amount_atomic:'100',claim_revision:1},requestsPath='/v1/referrals/me/payout-requests';const saved=await request(requestsPath,post(body));assert.equal(saved.status,200);const value=await saved.json();assert.equal(value.state,'requested');assert.equal(value.payout,null);assert.equal(value.claim_id,claim.claim_id);assert.equal((await request(requestsPath,post(body))).status,200);
 assert.equal((await request(requestsPath,post({...body,amount_atomic:'99'}))).status,409);assert.equal((await request(requestsPath+'/'+body.request_id,{headers:{'X-Referral-Capability':other}})).status,403);assert.equal((await request(requestsPath+'?limit=21',{headers})).status,400);
 const history=await (await request(requestsPath+'?limit=1',{headers})).json();assert.equal(history.requests[0].request_id,body.request_id);assert.equal((await request(requestsPath+'/'+body.request_id,{headers})).status,200);
 const after=await (await request('/v1/referrals/me/earnings',{headers})).json();assert.equal(after.reserved_atomic,'0');assert.equal(after.available_atomic,'100');assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM platform_referral_payouts').get().n,0);
 const stored=JSON.stringify(db.sqlite.prepare('SELECT * FROM platform_payout_requests').all())+JSON.stringify(db.sqlite.prepare('SELECT * FROM platform_referral_wallet_proofs').all());assert(!stored.includes(capability));assert(!stored.includes(signature));assert(!JSON.stringify(history).includes('request_hash'));
 const blocked=createPlatform({db,origin,feedbackLimit:async()=>false});assert.equal((await blocked(new Request(origin+requestsPath,post({...body,request_id:uuid()})),'fixture')).status,429);
 for(const path of ['/v1/owner/payouts','/v1/referrals/me/payout-wallet/approve'])assert.equal((await request(path,post({}))).status,404);
}finally{db.close();}});

test('paid request OpenAPI response accepts canonical chain quantities and rejects decimal or padded evidence',()=>{
 const require=createRequire(import.meta.url),sdkRequire=createRequire(require.resolve('@modelcontextprotocol/sdk/package.json')),Ajv=sdkRequire('ajv/dist/2020.js').default;
 const ajv=new Ajv({allErrors:true,strict:false,ownProperties:true,validateFormats:false}),document={paths:{}},header={name:'X-Referral-Capability',in:'header',required:true,schema:{type:'string'}};
 addBeneficiaryPayoutOpenApi(document,header,header);
 const schema=document.paths['/v1/referrals/me/payout-requests/{request_id}'].get.responses[200].content['application/json'].schema,validate=ajv.compile(schema);
 const receipt={transaction_hash:'0x'+'a'.repeat(64),block_hash:'0x'+'b'.repeat(64),block_number:'0x12d687',log_index:'0x0',checked_at:date,basis:'finalized_canonical_base_usdc_transfer'};
 const fixture={api_version:'1',request_id:uuid(),beneficiary_kind:'referral',subject_id:'ref_'+uuid(),amount_atomic:'100',network:BASE_NETWORK,asset:BASE_USDC.toLowerCase(),claim_id:uuid(),claim_revision:1,created_at:date,state:'paid',payout:{payout_id:uuid(),batch_id:uuid(),state:'paid',revision:4,amount_atomic:'100',created_at:date,receipt},payment_effect:'none'};
 assert.equal(validate(fixture),true,JSON.stringify(validate.errors));
 for(const field of ['block_number','log_index'])for(const value of ['123','0x00','0x01','0xA','0x'+'a'.repeat(65)]){const invalid=structuredClone(fixture);invalid.payout.receipt[field]=value;assert.equal(validate(invalid),false,field+': '+value);}
 const maximum=structuredClone(fixture);maximum.payout.receipt.block_number='0x'+'f'.repeat(64);assert.equal(validate(maximum),true,JSON.stringify(validate.errors));
});
