import test from 'node:test';
import assert from 'node:assert/strict';
import {z} from 'zod';
import {encodePaymentSignatureHeader} from '@x402/core/http';
import {database} from '../scripts/local-db.js';
import {createPlatform} from '../src/app.js';
import {submitTool,CREATOR_TERMS} from '../src/submissions.js';
import {submitToolUpdate} from '../src/tool-updates.js';
import {recordCreatorInstallation} from '../src/creator-installations.js';
import {successContractPin} from '../src/contract-pins.js';
import {paymentRequirements,BASE_NETWORK,BASE_USDC} from '../src/payment-config.js';
import {hash} from '../src/telemetry.js';
import {getCreatorEarnings} from '../src/creator-payouts.js';
import {service} from '../src/service.js';
const origin='https://example.invalid',capability='atbc_'+Buffer.alloc(32,43).toString('base64url'),reviewer='local-owner',payer='0x'+'22'.repeat(20),payTo='0x'+'11'.repeat(20),key=()=>crypto.randomUUID();
const proposal={name:'Local lifecycle fixture',summary:'Local compiled adapter lifecycle test',endpoint_url:'https://fixture.example/api',input_schema:{type:'object'},output_schema:{type:'object'}};
async function fixture(){
 const db=database(),date=new Date().toISOString();db.sqlite.exec('PRAGMA foreign_keys=ON');
 const s=await submitTool({db,body:{request_id:key(),creator_secret_hash:await hash(capability),terms_version:CREATOR_TERMS.terms_version,proposal},capability,client:'local-lifecycle'});
 await db.prepare('INSERT INTO platform_submission_decisions VALUES(?,?,?,?,?,?,?,?,?,?)').bind(key(),s.submission_id,reviewer,await hash(key()),'a'.repeat(64),0,1,'approved','Local fixture',date).run();
 const product={id:s.tool_id,name:'Local fixture',description:'Compiled local fixture',version:'0.1.0',status:'active',tags:[],provider:{id:'local-creator',type:'creator'},pricing:{payments_enabled:true,minimum_amount_atomic:'10000'},outcome:{success_criterion:'Output n is nonnegative'},input_schema:{type:'object'},output_schema:{type:'object'}};
 const counts={verify:0,settle:0,run:0},handler={creatorAdapterId:'compiled-local-v1',creatorArtifactSha256:'a'.repeat(64),creatorContractSha256:(await successContractPin(product)).sha256,input:z.strictObject({n:z.number().int()}),output:z.strictObject({n:z.number().int()}),run:async input=>{counts.run++;if(f.runHook)await f.runHook();return input;},success:output=>output.n>=0};
 handler.preview=result=>({n:result.n});
 const payments={enabled:true,live:true,receiverConfirmed:true,network:BASE_NETWORK,asset:BASE_USDC,payTo};
 const f={db,product,handler,counts,verifyHook:null,runHook:null};
 const app=createPlatform({db,origin,catalog:[product],handlers:{[product.id]:handler},payments,paymentAdapterFactory:async ({amount})=>({requirements:paymentRequirements(product,payments,amount),verify:async()=>{counts.verify++;if(f.verifyHook)await f.verifyHook();return {isValid:true,payer};},settle:async()=>{counts.settle++;return {success:true,network:BASE_NETWORK,transaction:'0x'+'cc'.repeat(32),payer,amount};}})});
 f.request=(path,init={})=>app(new Request(origin+path,init),'local-lifecycle');f.path='/v1/products/'+product.id;
 f.install=(expectedRevision=0,extra={})=>recordCreatorInstallation({db,reviewer,requestId:key(),toolId:product.id,expectedRevision,action:'install',metadataRevision:0,metadataVersion:'0.1.0',adapterId:handler.creatorAdapterId,artifactSha256:handler.creatorArtifactSha256,successContractSha256:handler.creatorContractSha256,productVersion:product.version,...extra});
 f.suspend=(expectedRevision=1)=>recordCreatorInstallation({db,reviewer,requestId:key(),toolId:product.id,expectedRevision,action:'suspend'});
 f.quote=(amount='10001')=>f.request(f.path+'/quote',json({version:'0.1.0',input:{n:7},payment_amount_atomic:amount}));
 f.prepare=async()=>{const secret='atbp_'+Buffer.alloc(32,44).toString('base64url'),body={version:'0.1.0',input:{n:7},request_id:key(),prepare_secret_hash:await hash(secret)},init=json(body,{'X-Preparation-Capability':secret});return {invoke:()=>f.request(f.path+'/prepare',init),quote:prepared_id=>f.request(f.path+'/quote',json({version:'0.1.0',prepared_id,payment_amount_atomic:'10001'},{'X-Preparation-Capability':secret}))};};
 f.purchase=async()=>{const response=await f.quote();assert.equal(response.status,200,await response.clone().text());const quote=await response.json(),amount='10001',terms=paymentRequirements(product,payments,amount),seconds=Math.floor(Date.now()/1000),payload={x402Version:2,accepted:terms,payload:{signature:'0x'+'00'.repeat(65),authorization:{from:payer,to:payTo,value:amount,nonce:'0x'+key().replaceAll('-','').padEnd(64,'a'),validAfter:String(seconds-1),validBefore:String(seconds+300)}}},body={version:'0.1.0',input:{n:7},payment_amount_atomic:amount,max_charge_usdc_atomic:amount,quote_id:quote.quote_id},init=json(body,{'PAYMENT-SIGNATURE':encodePaymentSignatureHeader(payload),'Idempotency-Key':key(),'X-AgentToolbox-Sample':'synthetic'});return {invoke:()=>f.request(f.path+'/invoke',init),body,init};};
 return f;
}
const json=(body,headers={})=>({method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
async function inactive(f){const catalog=await(await f.request('/v1/products')).json();assert.equal(catalog.products.some(p=>p.id===f.product.id),false);assert.equal((await f.request(f.path+'/invoke')).status,404);assert.equal((await f.request(f.path+'/invoke',json({version:'0.1.0',input:{n:7},max_charge_usdc_atomic:'10000'}))).status,410);assert.ok((await f.quote()).status>=400);}
test('HTTP metadata approval stays inert until audited install; paid receipt freezes 90% creator and installation',async()=>{
 const f=await fixture();try{await inactive(f);assert.deepEqual(f.counts,{verify:0,settle:0,run:0});assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_quotes').get().n,0);const install=await f.install();const catalog=await(await f.request('/v1/products')).json();assert.equal(catalog.products.some(p=>p.id===f.product.id),true);assert.equal((await f.request(f.path+'/invoke')).status,402);const purchase=await f.purchase(),response=await purchase.invoke();assert.equal(response.status,200,await response.clone().text());const result=await response.json();assert.equal(result.payment.amount_settled_atomic,'10001');const p=f.db.sqlite.prepare('SELECT * FROM platform_payments').get(),allocation=f.db.sqlite.prepare('SELECT * FROM platform_creator_allocations').get();assert.equal(p.creator_installation_id,install.installation_id);assert.equal(p.creator_install_revision,1);assert.equal(p.creator_tool_id,f.product.id);assert.equal(p.creator_share_bps,9000);assert.equal(allocation.creator_id,p.creator_id);assert.equal(allocation.share_bps,9000);assert.equal(allocation.gross_atomic,'10001');const earnings=await getCreatorEarnings({db:f.db,tool:f.product.id,capability});assert.equal(earnings.accrued_atomic,'9000');assert.equal(earnings.fractional_atom_numerator,'9');assert.deepEqual(f.counts,{verify:1,settle:1,run:1});}finally{f.db.close();}
});
test('HTTP suspension disables fresh purchases while exact settled replay survives without payment or execution',async()=>{
 const f=await fixture();try{await f.install();const purchase=await f.purchase(),first=await purchase.invoke();assert.equal(first.status,200);const original=await first.json();await f.suspend();await inactive(f);const replay=await purchase.invoke();assert.equal(replay.status,200,await replay.clone().text());assert.deepEqual(await replay.json(),original);const changed={...purchase.init,body:JSON.stringify({...purchase.body,input:{n:8}})};assert.equal((await f.request(f.path+'/invoke',changed)).status,409);assert.deepEqual(f.counts,{verify:1,settle:1,run:1});assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_payments').get().n,1);}finally{f.db.close();}
});
test('HTTP metadata update approval leaves installed execution version and beneficiary unchanged',async()=>{
 const f=await fixture();try{const install=await f.install(),u=await submitToolUpdate({db:f.db,tool:f.product.id,capability,client:'lifecycle-update',body:{request_id:key(),creator_secret_hash:await hash(capability),terms_version:CREATOR_TERMS.terms_version,base_version:'0.1.0',expected_head_revision:0,proposed_version:'0.2.0',proposal:{...proposal,name:'New metadata only'}}});await f.db.prepare('INSERT INTO platform_tool_update_decisions VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(key(),u.update_id,reviewer,await hash(key()),'c'.repeat(64),0,1,0,'approved','Local update',new Date().toISOString()).run();const detail=await(await f.request(f.path)).json();assert.equal(detail.product.version,'0.1.0');const purchase=await f.purchase(),response=await purchase.invoke();assert.equal(response.status,200,await response.clone().text());assert.equal((await response.json()).version,'0.1.0');assert.equal(f.db.sqlite.prepare('SELECT creator_installation_id FROM platform_payments').get().creator_installation_id,install.installation_id);}finally{f.db.close();}
});
for(const action of ['suspend','reinstall'])test('HTTP '+action+' during verification rejects stale installation before execution or settlement',async()=>{
 const f=await fixture();try{await f.install();const purchase=await f.purchase();f.verifyHook=()=>action==='suspend'?f.suspend():f.install(1);const response=await purchase.invoke();assert.equal(response.status,409,await response.clone().text());assert.equal((await response.json()).error.code,'creator_installation_changed');assert.deepEqual(f.counts,{verify:1,settle:0,run:0});assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_payments').get().n,0);assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_live_receipts').get().n,0);assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_creator_allocations').get().n,0);}finally{f.db.close();}
});
for(const change of ['same artifact revision','different artifact'])test('HTTP preparation stays bound to its installation after '+change+' reinstall',async()=>{
 const f=await fixture();try{const first=await f.install(),preparation=await f.prepare(),response=await preparation.invoke();assert.equal(response.status,200,await response.clone().text());const prepared=await response.json(),row=f.db.sqlite.prepare('SELECT * FROM platform_preparations WHERE prepared_id=?').get(prepared.prepared_id);assert.equal(row.state,'ready');assert.equal(row.creator_installation_id,first.installation_id);assert.equal(row.creator_install_revision,1);assert.equal((await preparation.quote(prepared.prepared_id)).status,200);if(change==='different artifact')f.handler.creatorArtifactSha256='d'.repeat(64);const next=await f.install(1);assert.notEqual(next.installation_id,first.installation_id);for(const rejected of [await preparation.invoke(),await preparation.quote(prepared.prepared_id)]){assert.equal(rejected.status,409,await rejected.clone().text());assert.equal((await rejected.json()).error.code,'creator_installation_changed');}assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_quotes').get().n,1);assert.deepEqual(f.counts,{verify:0,settle:0,run:1});assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_payments').get().n,0);}finally{f.db.close();}
});
test('HTTP suspension during preparation execution never publishes a ready result',async()=>{
 const f=await fixture();try{await f.install();const preparation=await f.prepare();f.runHook=()=>f.suspend();const response=await preparation.invoke();assert.ok([409,503].includes(response.status),await response.clone().text());assert.ok(['creator_installation_changed','creator_adapter_unavailable'].includes((await response.json()).error.code));const row=f.db.sqlite.prepare('SELECT * FROM platform_preparations').get();assert.equal(row.state,'failed');assert.equal(row.result_json,null);assert.equal(row.preview_json,null);assert.deepEqual(f.counts,{verify:0,settle:0,run:1});assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_payments').get().n,0);assert.equal(f.db.sqlite.prepare('SELECT count(*) n FROM platform_quotes').get().n,0);}finally{f.db.close();}
});
test('raw free service admission rejects unaudited creator and foreign seller before execution',async()=>{
 const db=database();try{let executions=0;const handler={input:z.strictObject({n:z.number().int()}),output:z.strictObject({n:z.number().int()}),run:async input=>{executions++;return input;},success:()=>true};for(const identity of [{id:'creator-'+key(),provider:{id:'local-creator',type:'creator'}},{id:'foreign-free',provider:{id:'foreign-seller',type:'first_party'}}]){const product={...identity,version:'0.1.0',status:'active',pricing:{payments_enabled:false},outcome:{success_criterion:'Local output succeeds'}},api=service({db,catalog:[product],handlers:{[product.id]:handler}});await assert.rejects(api.invoke(product.id,{version:'0.1.0',input:{n:1},max_charge_usdc_atomic:'0'},key()),e=>e.code==='creator_adapter_unavailable');}assert.equal(executions,0);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_runs').get().n,0);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_payments').get().n,0);}finally{db.close();}
});
test('HTTP free example requires audit for marked creator handlers but preserves first-party replay history',async()=>{
 const db=database();try{let executions=0;const product={id:'docs-pack',version:'0.1.0',status:'active',name:'Local example',tags:[],provider:{id:'agenttoolbox',type:'first_party'},pricing:{payments_enabled:false},outcome:{success_criterion:'Local example output'},example_input:{n:1}},handler={input:z.strictObject({n:z.number().int()}),output:z.strictObject({n:z.number().int()}),run:async input=>{executions++;return input;},success:()=>true},app=createPlatform({db,origin,catalog:[product],handlers:{'docs-pack':handler}}),request=exampleKey=>app(new Request(origin+'/v1/products/docs-pack/example',{headers:{'Idempotency-Key':exampleKey}}),'local-free-example');
 handler.creatorAdapterId='unaudited-local';let rejected=await request(key());assert.equal(rejected.status,503);assert.equal((await rejected.json()).error.code,'creator_adapter_unavailable');assert.equal(executions,0);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_examples').get().n,0);
 delete handler.creatorAdapterId;const replayKey=key(),response=await request(replayKey);assert.equal(response.status,200,await response.clone().text());const original=await response.json();assert.equal(executions,1);handler.creatorAdapterId='unaudited-changed-marker';const replay=await request(replayKey);assert.equal(replay.status,200,await replay.clone().text());assert.deepEqual(await replay.json(),original);assert.equal(executions,1);rejected=await request(key());assert.equal(rejected.status,503);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_examples').get().n,1);assert.equal(db.sqlite.prepare('SELECT state FROM platform_examples').get().state,'completed');
 }finally{db.close();}
});
test('creator earnings execution status follows active audited installation through suspension',async()=>{
 const f=await fixture();try{const earnings=()=>getCreatorEarnings({db:f.db,tool:f.product.id,capability});assert.equal((await earnings()).execution_status,'metadata_only_not_earning');await f.install();assert.equal((await earnings()).execution_status,'installed_adapter');await f.suspend();assert.equal((await earnings()).execution_status,'metadata_only_not_earning');assert.equal((await earnings()).gross_atomic,'0');assert.deepEqual(f.counts,{verify:0,settle:0,run:0});}finally{f.db.close();}
});
