import test from 'node:test';
import assert from 'node:assert/strict';
import {z} from 'zod';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {encodePaymentSignatureHeader} from '@x402/core/http';
import {database} from '../scripts/local-db.js';
import {submitTool,CREATOR_TERMS} from '../src/submissions.js';
import {createReviewedCreatorRegistry,reviewedCreatorRegistry} from '../src/reviewed-creator-adapters.js';
import {createPlatform} from '../src/app.js';
import {successContractPin} from '../src/contract-pins.js';
import {paymentRequirements,BASE_NETWORK,BASE_USDC} from '../src/payment-config.js';
import {claimWallet,challengeWallet,verifyWallet} from '../src/creator-wallets.js';
import {getCreatorEarnings} from '../src/creator-payouts.js';
import {requestPayout,getPayoutRequest} from '../src/payout-requests.js';
import * as operator from '../src/payout-operator.js';
import {hash} from '../src/telemetry.js';
const key=()=>crypto.randomUUID(),origin='https://example.invalid',reviewer='local-owner',sourceAddress='0x'+'11'.repeat(20),payer='0x'+'22'.repeat(20);
const json=(body,headers={})=>({method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
test('reviewed compiled creator sale earns funds and completes private finalized payout through real state machines',async()=>{
 const db=database(),date=new Date().toISOString(),now=()=>new Date(date),capability='atbc_'+Buffer.alloc(32,51).toString('base64url'),account=privateKeyToAccount(generatePrivateKey()),counts={execute:0,verify:0,settle:0};try{
 db.sqlite.exec('PRAGMA foreign_keys=ON');assert.deepEqual((await reviewedCreatorRegistry).getRuntime(),{products:[],handlers:{}});
 const input=z.strictObject({value:z.number().int()}),output=z.strictObject({doubled:z.number().int()}),proposal={name:'Local reviewed integer tool',summary:'Local synthetic reviewed seller fixture',endpoint_url:'https://fixture.example/api',input_schema:z.toJSONSchema(input),output_schema:z.toJSONSchema(output)};
 const submission=await submitTool({db,body:{request_id:key(),creator_secret_hash:await hash(capability),terms_version:CREATOR_TERMS.terms_version,proposal},capability,client:'local-sale-payout',now});
 await db.prepare('INSERT INTO platform_submission_decisions VALUES(?,?,?,?,?,?,?,?,?,?)').bind(key(),submission.submission_id,reviewer,await hash(key()),'a'.repeat(64),0,1,'approved','Local compiled source reviewed',date).run();
 const product={id:submission.tool_id,version:'0.1.0',name:proposal.name,summary:proposal.summary,status:'active',tags:[],provider:{id:'local-reviewed-seller',type:'creator'},pricing:{payments_enabled:true,minimum_amount_atomic:'10000'},outcome:{success_criterion:'Output doubles the supplied integer'},input_schema:z.toJSONSchema(input),output_schema:z.toJSONSchema(output)},pin=await successContractPin(product),manifestId='local-reviewed-sale-v1';
 const registry=await createReviewedCreatorRegistry([{manifestId,toolId:product.id,metadataRevision:0,metadataVersion:'0.1.0',sourceCommit:'a'.repeat(40),artifactSha256:'b'.repeat(64),successContractSha256:pin.sha256,productVersion:'0.1.0',adapterId:'local-compiled-integer-v1',product,handler:{input,output,run:async({value})=>{counts.execute++;return {doubled:value*2};},success:r=>Number.isInteger(r.doubled),creatorAdapterId:'local-compiled-integer-v1',creatorArtifactSha256:'b'.repeat(64),creatorContractSha256:pin.sha256}}]);
 const runtime=registry.getRuntime(),payments={enabled:true,live:true,receiverConfirmed:true,network:BASE_NETWORK,asset:BASE_USDC,payTo:sourceAddress},app=createPlatform({db,origin,catalog:runtime.products,handlers:runtime.handlers,payments,paymentAdapterFactory:async({amount})=>({requirements:paymentRequirements(product,payments,amount),verify:async()=>{counts.verify++;return {isValid:true,payer};},settle:async()=>{counts.settle++;return {success:true,network:BASE_NETWORK,transaction:'0x'+'cc'.repeat(32),payer,amount};}})}),request=(path,init={})=>app(new Request(origin+path,init),'local-sale-payout'),path='/v1/products/'+product.id;
 assert.equal((await request(path+'/invoke')).status,404);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_creator_allocations').get().n,0);const installation=await registry.install({db,reviewer,requestId:key(),manifestId,expectedRevision:0,now});assert.equal((await request(path+'/invoke')).status,402);
 const quoted=await request(path+'/quote',json({version:'0.1.0',input:{value:7},payment_amount_atomic:'10001'}));assert.equal(quoted.status,200,await quoted.clone().text());const quote=await quoted.json(),terms=paymentRequirements(product,payments,'10001'),seconds=Math.floor(Date.now()/1000),payload={x402Version:2,accepted:terms,payload:{signature:'0x'+'00'.repeat(65),authorization:{from:payer,to:sourceAddress,value:'10001',nonce:'0x'+key().replaceAll('-','').padEnd(64,'a'),validAfter:String(seconds-1),validBefore:String(seconds+300)}}},paidRequest=json({version:'0.1.0',input:{value:7},payment_amount_atomic:'10001',max_charge_usdc_atomic:'10001',quote_id:quote.quote_id},{'PAYMENT-SIGNATURE':encodePaymentSignatureHeader(payload),'Idempotency-Key':key(),'X-AgentToolbox-Sample':'synthetic'}),sale=await request(path+'/invoke',paidRequest);assert.equal(sale.status,200,await sale.clone().text());assert.deepEqual((await sale.json()).output,{doubled:14});assert.equal((await request(path+'/invoke',paidRequest)).status,200);assert.deepEqual(counts,{execute:1,verify:1,settle:1});
 const payment=db.sqlite.prepare('SELECT * FROM platform_payments').get(),allocation=db.sqlite.prepare('SELECT * FROM platform_creator_allocations').get();assert.equal(payment.state,'settled');assert.equal(payment.creator_installation_id,installation.installation_id);assert.equal(allocation.gross_atomic,'10001');assert.equal(allocation.share_bps,9000);const earnings=await getCreatorEarnings({db,tool:product.id,capability});assert.equal(earnings.accrued_atomic,'9000');assert.equal(earnings.fractional_atom_numerator,'9');
 const claim=await claimWallet({db,capability,body:{request_id:key(),expected_revision:0,network:BASE_NETWORK,address:account.address},now}),challenge=await challengeWallet({db,capability,body:{request_id:key(),claim_revision:1},origin,now});await verifyWallet({db,capability,body:{challenge_id:challenge.challenge_id,signature:await account.signMessage({message:challenge.message})},origin,now});await operator.approvePayoutWallet({db,kind:'creator',claimId:claim.claim_id,reviewer,requestId:key(),now});
 const requested=await requestPayout({db,kind:'creator',tool:product.id,capability,body:{request_id:key(),amount_atomic:'9000',claim_revision:1},now});let payout=(await operator.reservePayoutRequests({db,kind:'creator',requestIds:[requested.request_id],reviewer,requestId:key(),sourceAddress,now})).items[0];const event=(extra={})=>({db,kind:'creator',payoutId:payout.payout_id,reviewer,requestId:key(),expectedRevision:payout.revision,now,...extra});payout=await operator.authorizeOperatorPayout(event());const manifest=await operator.getOperatorPayoutManifest({db,kind:'creator',payoutId:payout.payout_id,reviewer});assert.equal(manifest.amount_atomic,'9000');assert.equal(manifest.to,account.address.toLowerCase());assert.equal(manifest.signature,null);assert.equal(manifest.broadcast,false);
 const transactionHash='0x'+'33'.repeat(32),blockHash='0x'+'44'.repeat(32),finalHash='0x'+'55'.repeat(32),topic=a=>'0x'+a.slice(2).padStart(64,'0'),data='0x'+BigInt(manifest.amount_atomic).toString(16).padStart(64,'0'),tx={hash:transactionHash,chainId:'0x2105',nonce:'0x7',from:manifest.from,to:manifest.asset,value:'0x0',input:manifest.transaction.data,blockNumber:'0x10',blockHash,transactionIndex:'0x0'},log={address:manifest.asset,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',topic(manifest.from),topic(manifest.to)],data,transactionHash,blockNumber:'0x10',blockHash,transactionIndex:'0x0',logIndex:'0x2',removed:false},receipt={transactionHash,from:manifest.from,to:manifest.asset,status:'0x1',blockNumber:'0x10',blockHash,transactionIndex:'0x0',logs:[log]},finalized={number:'0x20',hash:finalHash},canonical={number:'0x10',hash:blockHash,transactions:[transactionHash],timestamp:'0x'+(BigInt(Math.floor(Date.parse(date)/1000))+1n).toString(16)},calls=[];
 const rpc=async(method,params)=>{calls.push(method);if(method==='eth_chainId')return '0x2105';if(method==='eth_getTransactionByHash')return tx;if(method==='eth_getTransactionReceipt')return receipt;if(method==='eth_getBlockByNumber')return params[0]==='finalized'||params[0]==='0x20'?finalized:canonical;throw Error('unexpected RPC method');};payout=await operator.registerOperatorPayoutTransaction(event({rpc,transactionHash}));payout=await operator.reconcileOperatorPayout(event({rpc,transactionHash}));assert.equal(payout.state,'paid');assert.ok(calls.every(method=>['eth_chainId','eth_getTransactionByHash','eth_getTransactionReceipt','eth_getBlockByNumber'].includes(method)));
 const status=await getPayoutRequest({db,kind:'creator',tool:product.id,capability,id:requested.request_id});assert.equal(status.state,'paid');assert.equal(status.payout.receipt.transaction_hash,transactionHash);assert.equal(status.payout.receipt.basis,'finalized_canonical_base_usdc_transfer');const finalEarnings=await getCreatorEarnings({db,tool:product.id,capability});assert.equal(finalEarnings.confirmed_paid_atomic,'9000');assert.equal(finalEarnings.available_atomic,'0');assert.equal(finalEarnings.reserved_atomic,'0');assert.equal(finalEarnings.fractional_atom_numerator,'9');assert.deepEqual(counts,{execute:1,verify:1,settle:1});assert.deepEqual(db.sqlite.prepare('PRAGMA foreign_key_check').all(),[]);
 }finally{db.close();}
});
