import test from 'node:test';
import assert from 'node:assert/strict';
import {privateKeyToAccount} from 'viem/accounts';
import {parseSiweMessage} from 'viem/siwe';
import {database} from '../scripts/local-db.js';
import {hash} from '../src/telemetry.js';
import {claimWallet,getWallet,challengeWallet,verifyWallet,approveWallet} from '../src/creator-wallets.js';
const capability='atbc_'+Buffer.alloc(32,19).toString('base64url'),other='atbc_'+Buffer.alloc(32,20).toString('base64url'),origin='https://wallet.example.invalid',date='2026-10-07T08:00:00.000Z',now=()=>new Date(date),account=privateKeyToAccount('0x'+'11'.repeat(32)),request=()=>crypto.randomUUID();
async function setup(){const db=database();await db.prepare('INSERT INTO platform_creators VALUES(?,?,?)').bind('fixture-creator',await hash(capability),date).run();return db;}
const claim=(db,expected_revision=0,extra={})=>claimWallet({db,capability,now,body:{request_id:request(),expected_revision,network:'eip155:8453',address:account.address,...extra}});
const challenge=(db,revision=1)=>challengeWallet({db,capability,origin,now,body:{request_id:request(),claim_revision:revision}});
test('wallet CAS, scoped replay, immutable audit and private bounded history',async()=>{const db=await setup();try{const body={request_id:request(),expected_revision:0,network:'eip155:8453',address:account.address},args={db,capability,body,now};const [a,b]=await Promise.all([claimWallet(args),claimWallet(args)]);assert.equal(a.claim_id,b.claim_id);assert.equal(a.ownership_status,'unverified');await assert.rejects(claimWallet({...args,body:{...body,address:'0x'+'22'.repeat(20)}}),e=>e.status===409);await assert.rejects(claim(db),e=>e.status===409);const raced=await Promise.allSettled([claim(db,1),claim(db,1)]);assert.equal(raced.filter(r=>r.status==='fulfilled').length,1);await assert.rejects(getWallet({db,capability:other}),e=>e.status===403);const result=await getWallet({db,capability,params:{limit:1}});assert.equal(result.history.length,1);assert(result.next_cursor);assert.equal((await getWallet({db,capability,params:{limit:1,cursor:result.next_cursor}})).history[0].revision,1);assert(!JSON.stringify(result).includes('fixture-creator'));for(const sql of ['UPDATE platform_creator_wallet_claims SET revision=3','DELETE FROM platform_creator_wallet_claims'])assert.throws(()=>db.sqlite.exec(sql),/immutable_wallet_audit/);assert(!JSON.stringify(db.sqlite.prepare('SELECT * FROM platform_creators').all()).includes(capability));}finally{db.close();}});
test('EOA proof is optional and distinct from current owner approval; signature never stored',async()=>{const db=await setup();try{const c=await claim(db);await assert.rejects(approveWallet({db,claimId:c.claim_id,reviewer:'fixture-owner',requestId:request(),now}),e=>e.status===409);const h=await challenge(db);assert.equal(h.message.split('\n')[1],account.address);assert(!h.message.includes('\\n'));const parsed=parseSiweMessage(h.message);assert.equal(parsed.domain,'wallet.example.invalid');assert.equal(parsed.address,account.address);assert.equal(parsed.uri,origin);assert.equal(parsed.chainId,8453);assert.equal(parsed.nonce.length,32);assert(h.message.includes('Chain ID: 8453'));assert(h.message.includes('payout-destination-proof'));assert(!h.message.includes('fixture-creator'));const signature=await account.signMessage({message:h.message}),args={db,capability,origin,now,body:{challenge_id:h.challenge_id,signature}};const results=await Promise.all([verifyWallet(args),verifyWallet(args)]);assert.equal(results[0].ownership_status,'eoa_signature_verified');assert.equal(results[0].owner_approval.status,'pending');assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM platform_creator_wallet_proofs').get().n,1);assert(!JSON.stringify(db.sqlite.prepare('SELECT * FROM platform_creator_wallet_proofs').all()).includes(signature));const approvalArgs={db,claimId:c.claim_id,reviewer:'fixture-owner',requestId:request(),now};const approval=await approveWallet(approvalArgs);assert.deepEqual(await approveWallet(approvalArgs),approval);assert.equal((await getWallet({db,capability})).wallet.owner_approval.status,'approved');await claim(db,1);await assert.rejects(approveWallet({...approvalArgs,requestId:request()}),e=>e.status===409);for(const table of ['challenges','proofs','approvals'])assert.throws(()=>db.sqlite.exec('DELETE FROM platform_creator_wallet_'+table),/immutable_wallet_audit/);}finally{db.close();}});
test('wrong domain, wrong signer, expiration, supersession and conflicting replay fail closed',async()=>{const db=await setup();try{await claim(db);const h=await challenge(db),signature=await account.signMessage({message:h.message}),args={db,capability,origin,now,body:{challenge_id:h.challenge_id,signature}};await assert.rejects(verifyWallet({...args,origin:'https://other.example.invalid'}),e=>e.status===409);const wrong=await privateKeyToAccount('0x'+'33'.repeat(32)).signMessage({message:h.message});await assert.rejects(verifyWallet({...args,body:{...args.body,signature:wrong}}),e=>e.code==='wallet_signature_invalid');await assert.rejects(verifyWallet({...args,now:()=>new Date('2026-10-07T08:05:00.000Z')}),e=>e.status===409);await verifyWallet(args);await assert.rejects(verifyWallet({...args,body:{...args.body,signature:wrong}}),e=>e.status===409);const next=await challenge(db);await claim(db,1);await assert.rejects(verifyWallet({...args,body:{challenge_id:next.challenge_id,signature:await account.signMessage({message:next.message})}}),e=>e.status===409);}finally{db.close();}});
test('database atomic write budget preserves replay and rejects invalid network/zero/checksum',async()=>{const db=await setup();try{for(const extra of [{network:'eip155:1'},{address:'0x'+'0'.repeat(40)},{address:account.address.replace('A','a')}]){if(extra.address===account.address)continue;await assert.rejects(claim(db,0,extra),e=>e.status===400);}await claim(db);const h=await challenge(db);for(let i=2;i<10;i++)await challenge(db);await assert.rejects(challenge(db),e=>e.status===429);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM platform_creator_wallet_challenges').get().n,9);assert.equal((await getWallet({db,capability})).wallet.revision,1);assert(h.expires_at);}finally{db.close();}});
test('global budget applies atomically across creators and all destination writes',async()=>{const db=await setup();try{const sql=db.sqlite.prepare('INSERT INTO platform_creator_wallet_claims VALUES(?,?,?,?,?,?,?,?,?)');for(let i=0;i<100;i++){const id='global-fixture-'+i;db.sqlite.prepare('INSERT INTO platform_creators VALUES(?,?,?)').run(id,'fixture-hash-'+i,date);for(let j=0;j<10;j++)sql.run(id+'-'+j,id,j+1,j,'eip155:8453',account.address,'key-'+j,'body-'+j,date);}await assert.rejects(claim(db),e=>e.status===429);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM platform_creator_wallet_claims').get().n,1000);}finally{db.close();}});

test('active reservation database rejection becomes a private revision conflict',async()=>{const db=await setup();try{await claim(db);db.sqlite.exec("CREATE TRIGGER fixture_reservation_guard BEFORE INSERT ON platform_creator_wallet_claims BEGIN SELECT RAISE(ABORT,'wallet_has_reserved_payout'); END;");await assert.rejects(claim(db,1),e=>e.status===409&&e.code==='wallet_conflict');assert.equal((await getWallet({db,capability})).wallet.revision,1);}finally{db.close();}});
