import test from 'node:test';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {privateKeyToAccount} from 'viem/accounts';
import {database} from '../scripts/local-db.js';
import {registerReferral,REFERRAL_TERMS} from '../src/referrals.js';
import {submitTool,CREATOR_TERMS} from '../src/submissions.js';
import {recordCreatorInstallation} from '../src/creator-installations.js';
import * as creatorWallet from '../src/creator-wallets.js';
import * as creatorPayout from '../src/creator-payouts.js';
import {claimWallet,challengeWallet,verifyWallet,approveWallet} from '../src/referral-wallets.js';
import {getReferralEarnings,proposePayoutBatch,authorizePayout,cancelPayout,markPayoutUnknown,getPayoutManifest,registerPayoutTransaction,reconcilePayout} from '../src/referral-payouts.js';
import {BASE_NETWORK,BASE_USDC,MAX_UINT256} from '../src/payment-config.js';
import {hash} from '../src/telemetry.js';
import {requestPayout,getPayoutRequest,listPayoutRequests,requestCursorEncode} from '../src/payout-requests.js';
import * as operator from '../src/payout-operator.js';
const date='2026-10-07T08:00:00.000Z',now=()=>new Date(date),origin='https://example.invalid',reviewer='local-owner',sourceAddress='0x'+'11'.repeat(20),account=privateKeyToAccount('0x'+'01'.repeat(32));
const key=()=>crypto.randomUUID(),conflict=e=>e.status===409;
async function creator(db,{proof=true,approval=true,wallet=true,legacy=false}={}){
 const capability='atbc_'+Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64url');
 const submission=await submitTool({db,body:{request_id:key(),creator_secret_hash:await hash(capability),terms_version:CREATOR_TERMS.terms_version,proposal:{name:'Local payout fixture',summary:'Local private accounting fixture',endpoint_url:'https://tool.example/api',input_schema:{type:'object'},output_schema:{type:'object'}}},capability,client:key(),now});
 await db.prepare('INSERT INTO platform_submission_decisions VALUES(?,?,?,?,?,?,?,?,?,?)').bind(key(),submission.submission_id,reviewer,await hash(key()),'a'.repeat(64),0,1,'approved','Local fixture',date).run();
 const tool=submission.tool_id;
 let installation;
 if(legacy)db.sqlite.prepare('UPDATE platform_creator_entitlements SET installed_adapter=? WHERE tool_id=?').run('local-fixture',tool);
 else installation=await recordCreatorInstallation({db,reviewer,requestId:key(),toolId:tool,expectedRevision:0,action:'install',metadataRevision:0,metadataVersion:'0.1.0',adapterId:'local-fixture',artifactSha256:'a'.repeat(64),successContractSha256:'b'.repeat(64),productVersion:'0.1.0',now});
 const creatorId=db.sqlite.prepare('SELECT creator_id FROM platform_creator_entitlements WHERE tool_id=?').get(tool).creator_id;
 if(!wallet)return {db,tool,creatorId,capability,installation};
 const claim=await creatorWallet.claimWallet({db,capability,body:{request_id:key(),expected_revision:0,network:BASE_NETWORK,address:account.address},now});
 if(proof){const challenge=await creatorWallet.challengeWallet({db,capability,body:{request_id:key(),claim_revision:1},origin,now});await creatorWallet.verifyWallet({db,capability,body:{challenge_id:challenge.challenge_id,signature:await account.signMessage({message:challenge.message})},origin,now});}
 if(approval&&proof)await creatorWallet.approveWallet({db,claimId:claim.claim_id,reviewer,requestId:key(),now});
 return {db,tool,creatorId,capability,claim,installation};
}
function creatorAccrue(f,gross='10001',{network=BASE_NETWORK,asset=BASE_USDC}={}){
 const operation=key(),transaction='0x'+operation.replaceAll('-','').padEnd(64,'a');
 f.db.sqlite.prepare(`INSERT INTO platform_payments(operation_id,product_id,version,key_hash,fingerprint,payment_digest,network,asset,payer,nonce,amount_atomic,receiver,state,created_at,updated_at,sample_kind,is_live,creator_tool_id,creator_id,creator_share_bps${f.installation?',creator_installation_id,creator_install_revision':''}) VALUES(?,?,'0.1.0',?,'fixture','fixture',?,?,?, ?,?,?,'settling',?,?,'synthetic',1,?,?,9000${f.installation?',?,?':''})`).run(operation,f.tool,key(),network,asset,sourceAddress,key(),gross,sourceAddress,date,date,f.tool,f.creatorId,...(f.installation?[f.installation.installation_id,f.installation.revision]:[]));
 const stmt=f.db.sqlite.prepare('INSERT INTO platform_payment_ledger VALUES(?,?,?,?,?,?,?,?,?,?,?)');for(const event of ['outcome_validated','settlement_reported'])stmt.run(key(),operation,f.tool,'0.1.0',event,network,asset,gross,transaction,'synthetic',date);
 f.db.sqlite.prepare("UPDATE platform_payments SET state='settled' WHERE operation_id=?").run(operation);
}
async function referrer(db,{proof=true,approval=true}={}){
 const capability='atbf_'+Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64url');
 const registration=await registerReferral({db,body:{terms_version:REFERRAL_TERMS.terms_version},capability,client:key(),now}),code=registration.referral_code;
 const claim=await claimWallet({db,capability,body:{request_id:key(),expected_revision:0,network:BASE_NETWORK,address:account.address},now});
 if(proof){const challenge=await challengeWallet({db,capability,body:{request_id:key(),claim_revision:1},origin,now});await verifyWallet({db,capability,body:{challenge_id:challenge.challenge_id,signature:await account.signMessage({message:challenge.message})},origin,now});}
 if(proof&&approval)await approveWallet({db,claimId:claim.claim_id,reviewer,requestId:key(),now});
 return {db,code,capability,claim};
}
function accrue(f,gross='10001',{network=BASE_NETWORK,asset=BASE_USDC}={}){
 const operation=key(),transaction='0x'+operation.replaceAll('-','').padEnd(64,'a');
 f.db.sqlite.prepare(`INSERT INTO platform_payments(operation_id,product_id,version,key_hash,fingerprint,payment_digest,network,asset,payer,nonce,amount_atomic,receiver,state,created_at,updated_at,sample_kind,is_live,referral_code,referral_terms_version,referral_share_bps) VALUES(?,'docs-pack','0.1.0',?,'fixture','fixture',?,?,?,?,?,?,'settling',?,?,'synthetic',1,?,?,100)`).run(operation,key(),network,asset,sourceAddress,key(),gross,sourceAddress,date,date,f.code,REFERRAL_TERMS.terms_version);
 const stmt=f.db.sqlite.prepare('INSERT INTO platform_payment_ledger VALUES(?,?,?,?,?,?,?,?,?,?,?)');for(const event of ['outcome_validated','settlement_reported'])stmt.run(key(),operation,'docs-pack','0.1.0',event,network,asset,gross,transaction,'synthetic',date);
 f.db.sqlite.prepare("UPDATE platform_payments SET state='settled' WHERE operation_id=?").run(operation);
}
const earnings=f=>getReferralEarnings({db:f.db,capability:f.capability});
const propose=(f,amount='100',extra={})=>proposePayoutBatch({db:f.db,reviewer,requestId:key(),sourceAddress,items:[{referral_code:f.code,amount_atomic:amount}],now,...extra});
const event=(f,p,extra={})=>({db:f.db,payoutId:p.payout_id,reviewer,requestId:key(),expectedRevision:p.revision,now,...extra});
function chain(p,transactionHash='0x'+'33'.repeat(32),nonce='0x7'){
 const blockHash='0x'+'44'.repeat(32),finalHash='0x'+'55'.repeat(32),topic=a=>'0x'+a.slice(2).padStart(64,'0'),data='0x'+BigInt(p.amount_atomic).toString(16).padStart(64,'0');
 const tx={hash:transactionHash,chainId:'0x2105',nonce,from:sourceAddress,to:BASE_USDC,value:'0x0',input:'0xa9059cbb'+topic(account.address).slice(2)+data.slice(2),blockNumber:'0x10',blockHash,transactionIndex:'0x0'};
 const log={address:BASE_USDC,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',topic(sourceAddress),topic(account.address)],data,transactionHash,blockNumber:'0x10',blockHash,transactionIndex:'0x0',logIndex:'0x2',removed:false};
 const receipt={transactionHash,from:sourceAddress,to:BASE_USDC,status:'0x1',blockNumber:'0x10',blockHash,transactionIndex:'0x0',logs:[log]},canonical={number:'0x10',hash:blockHash,timestamp:'0x'+(BigInt(Date.parse(date)/1000)+1n).toString(16)},finalized={number:'0x20',hash:finalHash},calls=[];
 const f={tx,receipt,canonical,calls,transactionHash};f.rpc=async(method,params)=>{calls.push(method);if(method==='eth_chainId')return '0x2105';if(method==='eth_getTransactionByHash')return tx;if(method==='eth_getTransactionReceipt')return receipt;if(method==='eth_getBlockByNumber')return params[0]==='finalized'||params[0]==='0x20'?finalized:canonical;throw Error('unexpected RPC');};return f;
}
async function paid(f,p,txHash){p=await authorizePayout(event(f,p));const c=chain(p,txHash,txHash?'0x8':'0x7');p=await registerPayoutTransaction(event(f,p,c));return reconcilePayout(event(f,p,c));}
function local(name,fn){test(name,async()=>{const db=database();try{await fn(db);}finally{db.close();}});}
const subject=(f,kind)=>({db:f.db,kind,tool:kind==='creator'?f.tool:undefined,capability:f.capability});
const request=(f,kind,extra={})=>requestPayout({...subject(f,kind),body:{request_id:key(),amount_atomic:'100',claim_revision:1,...extra},now});
const read=(f,kind,id)=>getPayoutRequest({...subject(f,kind),id});
const reserve=(f,kind,ids,extra={})=>operator.reservePayoutRequests({db:f.db,kind,requestIds:ids,reviewer,requestId:key(),sourceAddress,now,...extra});
const ownerEvent=(f,kind,p,extra={})=>({kind,...event(f,p,extra)});
async function proofAndApproval(f,kind,revision=1){const wallet=kind==='creator'?creatorWallet:{challengeWallet,verifyWallet};const challenge=await wallet.challengeWallet({db:f.db,capability:f.capability,body:{request_id:key(),claim_revision:revision},origin,now});await wallet.verifyWallet({db:f.db,capability:f.capability,body:{challenge_id:challenge.challenge_id,signature:await account.signMessage({message:challenge.message})},origin,now});return operator.approvePayoutWallet({db:f.db,kind,claimId:f.claim.claim_id,reviewer,requestId:key(),now});}
const make=(db,kind,options={})=>kind==='creator'?creator(db,options):referrer(db,options);
const earn=(f,kind,amount='20000')=>kind==='creator'?creatorAccrue(f,amount):accrue(f,amount);
for(const kind of ['creator','referral'])local(kind+' request completes private request-to-finalized owner workflow without automatic send',async db=>{
 const f=await make(db,kind,{proof:false,approval:false});earn(f,kind);const r=await request(f,kind),owner=await operator.getPayoutRequestForOwner({db,reviewer,requestId:r.request_id});assert.equal(r.state,'requested');assert.equal(owner.wallet.ownership_status,'unverified');assert.equal(owner.wallet.owner_approved,false);await assert.rejects(reserve(f,kind,[r.request_id]),e=>e.code==='payout_wallet_not_approved');await proofAndApproval(f,kind);const requestId=key(),batch=await reserve(f,kind,[r.request_id],{requestId});assert.deepEqual(await reserve(f,kind,[r.request_id],{requestId}),batch);let p=batch.items[0];assert.equal((await read(f,kind,r.request_id)).state,'reserved');p=await operator.authorizeOperatorPayout(ownerEvent(f,kind,p));const manifest=await operator.getOperatorPayoutManifest({db,kind,payoutId:p.payout_id,reviewer});assert.equal(manifest.from,sourceAddress);assert.equal(manifest.to,account.address.toLowerCase());assert.equal(manifest.amount_atomic,'100');assert.equal(manifest.signature,null);assert.equal(manifest.broadcast,false);assert.throws(()=>db.sqlite.prepare(`UPDATE platform_${kind}_payouts SET destination_address=? WHERE payout_id=?`).run(sourceAddress,p.payout_id),/immutable_payout/);
 const c=chain(p),registration=ownerEvent(f,kind,p,c);p=await operator.registerOperatorPayoutTransaction(registration);const calls=c.calls.length;assert.deepEqual(await operator.registerOperatorPayoutTransaction(registration),p);assert.equal(c.calls.length,calls);const confirmation=ownerEvent(f,kind,p,c);p=await operator.reconcileOperatorPayout(confirmation);const confirmedCalls=c.calls.length;assert.deepEqual(await operator.reconcileOperatorPayout(confirmation),p);assert.equal(c.calls.length,confirmedCalls);const status=await read(f,kind,r.request_id);assert.equal(status.state,'paid');assert.equal(status.payout.receipt.transaction_hash,c.transactionHash);assert.equal(status.payout.receipt.basis,'finalized_canonical_base_usdc_transfer');assert.equal((await operator.readPayoutForOwner({db,kind,payoutId:p.payout_id,reviewer})).request_id,r.request_id);assert.equal((await operator.listPayoutRequestsForOwner({db,reviewer})).requests.length,0);
});
local('capabilities, forged fields, changed body and cross-kind request IDs cannot redirect a request',async db=>{
 const c=await creator(db),r=await referrer(db);earn(c,'creator');earn(r,'referral');const saved=await request(c,'creator');await assert.rejects(request(r,'referral',{request_id:saved.request_id}),conflict);await assert.rejects(read(r,'referral',saved.request_id),e=>e.status===404);await assert.rejects(reserve(r,'referral',[saved.request_id]),conflict);await assert.rejects(getPayoutRequest({...subject(c,'creator'),id:saved.request_id,capability:r.capability}),e=>e.status===403);for(const extra of [{amount_atomic:'99'},{claim_revision:2}])await assert.rejects(request(c,'creator',{request_id:saved.request_id,...extra}),conflict);for(const extra of [{address:sourceAddress},{state:'paid'},{network:'eip155:1'},{subject_id:r.code},{share_bps:9999},{payout_id:key()}])await assert.rejects(request(c,'creator',extra),e=>e.status===400);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_payout_requests').get().n,1);assert.throws(()=>db.sqlite.exec("UPDATE platform_payout_requests SET amount_atomic='1'"),/immutable_payout_request/);
});
for(const kind of ['creator','referral'])local(kind+' wallet changes between request and reservation roll back batch and payout',async db=>{
 const f=await make(db,kind);earn(f,kind);const r=await request(f,kind),wallet=kind==='creator'?creatorWallet:{claimWallet};f.claim=await wallet.claimWallet({db,capability:f.capability,body:{request_id:key(),expected_revision:1,network:BASE_NETWORK,address:account.address},now});await proofAndApproval(f,kind,2);await assert.rejects(reserve(f,kind,[r.request_id]),conflict);assert.equal(db.sqlite.prepare(`SELECT count(*) n FROM platform_${kind}_payout_batches`).get().n,0);assert.equal(db.sqlite.prepare(`SELECT count(*) n FROM platform_${kind}_payouts`).get().n,0);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_payout_request_links').get().n,0);assert.equal((await read(f,kind,r.request_id)).state,'requested');
});
local('zero balance and conflicting available amount fail before request admission',async db=>{
 const f=await referrer(db,{proof:false,approval:false});await assert.rejects(request(f,'referral'),e=>e.code==='insufficient_payout_balance');accrue(f);await assert.rejects(request(f,'referral',{amount_atomic:'101'}),e=>e.code==='insufficient_payout_balance');await assert.rejects(request(f,'referral',{amount_atomic:'0'}),e=>e.status===400);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_payout_requests').get().n,0);
});
local('cancelled reservation consumes the request; fresh request is explicit and unknown holds reservation',async db=>{
 const f=await referrer(db);earn(f,'referral');const r=await request(f,'referral');let p=(await reserve(f,'referral',[r.request_id])).items[0];p=await operator.cancelOperatorPayout(ownerEvent(f,'referral',p));assert.equal((await read(f,'referral',r.request_id)).state,'cancelled');assert.equal((await request(f,'referral',{request_id:r.request_id})).state,'cancelled');await assert.rejects(reserve(f,'referral',[r.request_id]),conflict);const fresh=await request(f,'referral');p=(await reserve(f,'referral',[fresh.request_id])).items[0];p=await operator.authorizeOperatorPayout(ownerEvent(f,'referral',p));const uncertain=ownerEvent(f,'referral',p);p=await operator.markOperatorPayoutUnknown(uncertain);assert.deepEqual(await operator.markOperatorPayoutUnknown(uncertain),p);assert.equal((await read(f,'referral',fresh.request_id)).state,'unknown');await assert.rejects(operator.cancelOperatorPayout(ownerEvent(f,'referral',p)),conflict);const another=await request(f,'referral',{amount_atomic:'1'});await assert.rejects(reserve(f,'referral',[another.request_id]),conflict);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_referral_payout_transactions').get().n,0);
});
local('injected request-link persistence failure rolls back ledger and links; competing reservations commit once',async db=>{
 const f=await referrer(db);earn(f,'referral');const r=await request(f,'referral');db.sqlite.exec("CREATE TRIGGER fixture_link_failure BEFORE INSERT ON platform_payout_request_links BEGIN SELECT RAISE(ABORT,'fixture_disk_failure'); END");await assert.rejects(reserve(f,'referral',[r.request_id]),/fixture_disk_failure/);for(const table of ['platform_referral_payout_batches','platform_referral_payouts','platform_payout_request_links'])assert.equal(db.sqlite.prepare(`SELECT count(*) n FROM ${table}`).get().n,0);db.sqlite.exec('DROP TRIGGER fixture_link_failure');const race=await Promise.allSettled([reserve(f,'referral',[r.request_id]),reserve(f,'referral',[r.request_id])]);assert.equal(race.filter(r=>r.status==='fulfilled').length,1);assert.equal(race.find(r=>r.status==='rejected').reason.status,409);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_payout_request_links').get().n,1);
});
local('private and owner pagination stays bounded and cursor scopes reject cross-subject bypass',async db=>{
 const a=await referrer(db),b=await referrer(db);earn(a,'referral');earn(b,'referral');const records=await Promise.all(Array.from({length:5},()=>request(a,'referral',{amount_atomic:'1'})));await request(b,'referral',{amount_atomic:'1'});const first=await listPayoutRequests({...subject(a,'referral'),params:{limit:2}}),second=await listPayoutRequests({...subject(a,'referral'),params:{limit:2,cursor:first.next_cursor}}),third=await listPayoutRequests({...subject(a,'referral'),params:{limit:2,cursor:second.next_cursor}});assert.equal(first.requests.length,2);assert.equal(second.requests.length,2);assert.equal(third.requests.length,1);assert.equal(new Set([...first.requests,...second.requests,...third.requests].map(r=>r.request_id)).size,records.length);await assert.rejects(listPayoutRequests({...subject(b,'referral'),params:{cursor:first.next_cursor}}),e=>e.code==='invalid_cursor');await assert.rejects(listPayoutRequests({...subject(a,'referral'),params:{limit:21}}),e=>e.status===400);const owner=await operator.listPayoutRequestsForOwner({db,reviewer,params:{limit:2}});assert.equal(owner.requests.length,2);await assert.rejects(operator.listPayoutRequestsForOwner({db,reviewer:'other-owner',params:{cursor:owner.next_cursor}}),e=>e.code==='invalid_cursor');await assert.rejects(operator.listPayoutRequestsForOwner({db,reviewer,params:{kind:'creator',cursor:owner.next_cursor}}),e=>e.code==='invalid_cursor');const malformed=requestCursorEncode({scope:await hash('referral:'+a.code),created:date,id:records[0].request_id,extra:true});await assert.rejects(listPayoutRequests({...subject(a,'referral'),params:{cursor:malformed}}),e=>e.code==='invalid_cursor');
});
test('additive request migration preserves every earlier table and foreign key without historical backfill',async()=>{
 const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');const db={sqlite,prepare(sql){return {bind(...args){return {first:async()=>sqlite.prepare(sql).get(...args)??null,all:async()=>({results:sqlite.prepare(sql).all(...args)}),run:async()=>{const before=sqlite.prepare('SELECT total_changes() n').get().n;sqlite.prepare(sql).run(...args);return {meta:{changes:sqlite.prepare('SELECT total_changes() n').get().n-before}};}};}};},async batch(statements){sqlite.exec('BEGIN');try{const out=await Promise.all(statements.map(s=>s.all()));sqlite.exec('COMMIT');return out;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};try{
 const directory=new URL('../migrations/',import.meta.url);for(const name of readdirSync(directory).filter(n=>n.endsWith('.sql')&&n<'0016').sort())sqlite.exec(readFileSync(new URL(name,directory),'utf8'));
 const c=await creator(db),r=await referrer(db);creatorAccrue(c);accrue(r);let p=(await creatorPayout.proposePayoutBatch({db,reviewer,requestId:key(),sourceAddress,items:[{tool_id:c.tool,amount_atomic:'100'}],now})).items[0];p=await creatorPayout.authorizePayout(event(c,p));const ct=chain(p);p=await creatorPayout.registerPayoutTransaction(event(c,p,ct));await creatorPayout.reconcilePayout(event(c,p,ct));
 sqlite.prepare("INSERT INTO platform_feedback(id,key_hash,fingerprint,product_id,version,channel,link_status,sample_kind,message,created_at) VALUES(?,?,?,'docs-pack','0.1.0','http','unverified','synthetic',?,?)").run(key(),key(),'local-fingerprint','Private migration fixture',date);
 const tables=sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(r=>r.name),snapshot=()=>tables.map(name=>({name,rows:JSON.stringify(sqlite.prepare(`SELECT * FROM ${name} ORDER BY rowid`).all()),foreignKeys:JSON.stringify(sqlite.prepare(`PRAGMA foreign_key_list(${name})`).all())})),before=snapshot();sqlite.exec(readFileSync(new URL('0016_payout_requests.sql',directory),'utf8'));assert.deepEqual(snapshot(),before);assert.deepEqual(sqlite.prepare('PRAGMA foreign_key_check').all(),[]);
 assert.equal(sqlite.prepare('SELECT count(*) n FROM platform_payout_requests').get().n,0);assert.equal(sqlite.prepare('SELECT count(*) n FROM platform_payout_request_links').get().n,0);const requested=await request(r,'referral');assert.equal(requested.state,'requested');
 }finally{sqlite.close();}
});
local('daily request budget remains bounded while existing request replay stays available',async db=>{
 const f=await referrer(db);earn(f,'referral');const body={request_id:key(),amount_atomic:'1',claim_revision:1},first=await requestPayout({...subject(f,'referral'),body,now});for(let i=1;i<10;i++)await request(f,'referral',{amount_atomic:'1'});await assert.rejects(request(f,'referral',{amount_atomic:'1'}),e=>e.status===429&&e.code==='payout_request_budget_exhausted');assert.deepEqual(await requestPayout({...subject(f,'referral'),body,now}),first);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM platform_payout_requests').get().n,10);assert.equal((await listPayoutRequests({...subject(f,'referral'),params:{limit:20}})).requests.length,10);await assert.rejects(operator.listPayoutRequestsForOwner({db,reviewer:''}),e=>e.status===403);
});
