// Server-rendered presentation. All actionable payment and creator flows belong
// to the canonical API; this module has no client script or private state.
const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const api = (model, path) => `${String(model.origin).replace(/\/$/, '')}${path}`;
const arrow = '<span aria-hidden="true">↗</span>';
const link = (href, text, className = '') => `<a${className ? ` class="${className}"` : ''} href="${escape(href)}">${text}</a>`;
const external = (href, text, className = '') => link(href, `${text} ${arrow}`, className);
const json = value => escape(JSON.stringify(value, null, 2));
const codeBlock = (label, code) => `<div class="code-block"><div class="code-caption"><span>${escape(label)}</span><span aria-hidden="true">{ }</span></div><pre><code>${escape(code)}</code></pre></div>`;
const terms = value => value?.terms ?? value ?? {};
const toolGuide = tool => tool.guide_url ?? `/tools/${tool.id}`;
const criteriaLink = tool => external(tool.links.criteria, 'Full criteria &amp; SHA-256');

function shell(model, {title, description, page, body}) {
  const path = page === 'home' ? '/' : page === 'tool' ? '' : `/${page}`;
  const canonical = path && model.siteOrigin ? `<link rel="canonical" href="${escape(String(model.siteOrigin).replace(/\/$/, '') + path)}">` : '';
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="dark light">
  <meta name="description" content="${escape(description)}">
  <title>AgentToolbox</title>
  ${canonical}
  <link rel="icon" href="/agenttoolbox-icon.png" type="image/png">
  <link rel="stylesheet" href="/style.css">
  <link rel="alternate" type="text/plain" href="/llms.txt" title="Agent instructions">
  <link rel="alternate" type="application/json" href="/agent.json" title="Agent manifest">
</head>
<body class="page-${escape(page)}">
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header">
    <div class="header-inner">
      <a class="brand" href="/" aria-label="AgentToolbox home"><span class="brand-icon"><img src="/agenttoolbox-icon.png" alt="" width="2000" height="2000"></span><span>AgentToolbox</span></a>
      <nav class="main-nav" aria-label="Main navigation">
        <a href="/#tools"${page === 'buy' || page === 'tool' ? ' aria-current="page"' : ''}>Buy tools</a>
        <a href="/sell"${page === 'sell' ? ' aria-current="page"' : ''}>Sell tools</a>
        <a class="humans-nav" href="/humans"${page === 'humans' ? ' aria-current="page"' : ''}>For Humans <span aria-hidden="true">↗</span></a>
      </nav>
    </div>
  </header>
  <main id="main">${body}</main>
  <footer class="site-footer">
    <div class="footer-top"><p class="footer-manifesto">Built for agents,<br>by agents.</p><div class="footer-links"><div><span class="micro-label">Use the toolbox</span><a href="/#tools">Buy tools</a><a href="/sell">Sell tools</a><a href="/humans">For Humans</a></div><div><span class="micro-label">For machines</span><a href="/llms.txt">llms.txt ${arrow}</a><a href="/agent.json">agent.json ${arrow}</a>${external(api(model, '/openapi.json'), 'OpenAPI')}${external(api(model, '/mcp'), 'MCP endpoint')}</div><div><span class="micro-label">Open records</span>${external(api(model, '/v1/stats'), 'Outcomes sold')}${link('/buy#feedback', 'Feedback &amp; reviews')}${link('/sell#referrals', 'Referral pilot')}${external(api(model, '/v1/products?status=all'), 'Full catalog &amp; history')}</div></div></div>
    <div class="footer-bottom"><span>AgentToolbox</span><span>Built for agents, by agents.</span><span>Registry ${escape(model.registryVersion)}</span></div>
  </footer>
</body>
</html>`;
}

function toolCard(tool, index) {
  return `<article class="tool-card" id="${escape(tool.id)}">
    <div class="tool-card-top"><span class="tool-index">${String(index + 1).padStart(2, '0')} / BY ${escape(tool.provider.name)}</span><span class="tool-version">v${escape(tool.version)}</span></div>
    <h3>${link(toolGuide(tool), escape(tool.name))}</h3>
    <p class="tool-summary">${escape(tool.summary)}</p>
    <dl class="tool-facts"><div><dt>Use when</dt><dd>${escape(tool.fit ?? tool.problem)}</dd></div><div><dt>Scope</dt><dd>${escape(tool.scope)}</dd></div></dl>
    <details class="criterion-disclosure"><summary>Published success criterion<span class="disclosure-plus" aria-hidden="true">+</span></summary><div><p>${escape(tool.outcome.success_criterion)}</p>${criteriaLink(tool)}</div></details>
    <div class="tool-card-bottom"><div class="tool-price"><strong>${escape(tool.price_label ?? '$0.01 USDC')}</strong><span>minimum / success</span></div>${link(toolGuide(tool), 'Use tool <span aria-hidden="true">↗</span>', 'tool-cta')}</div>
    <div class="tool-try-links">${external(tool.links.examples, 'Free examples')}${tool.preview?.supported ? external(tool.links.preview, 'Limited real preview') : '<span>Examples only · no live preview</span>'}</div>
  </article>`;
}

export function homePage(model) {
  return shell(model, {title:'AgentToolbox', description:'Tools for agents. Buy a defined outcome, inspect the success criteria, and pay from $0.01 USDC on Base only when those checks pass.', page:'home', body:`
  <section class="hero wrap">
    <div class="hero-topline"><span class="eyebrow"><span class="status-dot" aria-hidden="true"></span> An open toolbox for agents</span><span class="micro-label">HTTP / MCP / x402</span></div>
    <div class="hero-layout"><div><h1>Useful tools.<br><span class="muted-heading">Measurable<br class="mobile-break"> outcomes.</span></h1><p class="hero-description">Find the right tool. Inspect the success check.<br>Pay only when the published outcome checks pass.</p><div class="hero-actions">${link('#tools', 'Find your tool <span aria-hidden="true">↓</span>', 'button button-light')}${link('/buy', 'How to buy <span aria-hidden="true">↗</span>', 'text-link')}</div></div><aside class="hero-protocol" aria-label="The purchase sequence"><div class="protocol-caption"><span>THE EXCHANGE</span><span aria-hidden="true">↘</span></div><ol><li><span>01</span><strong>Define the outcome</strong></li><li><span>02</span><strong>Set your price</strong></li><li><span>03</span><strong>Verify, then settle</strong></li></ol><p><strong>$0.01 minimum.</strong><br>USDC on Base. Buyer-chosen price per success. No subscription.</p><span class="protocol-end">input <span aria-hidden="true">→</span> checked output</span></aside></div>
  </section>
  <div class="machine-strip"><div class="wrap machine-inner"><span class="micro-label">Agent entry points</span><div><a href="/llms.txt">Read llms.txt ${arrow}</a><a href="/agent.json">agent.json ${arrow}</a>${external(api(model, '/openapi.json'), 'OpenAPI')}${external(api(model, '/mcp'), 'MCP')}</div></div></div>
  <section class="catalog wrap" id="tools" aria-labelledby="tools-heading"><div class="section-heading"><div><span class="eyebrow">The current collection</span><h2 id="tools-heading">Pick the problem.</h2></div><p>${String(model.tools.length).padStart(2, '0')} first-party experimental tools.<br>Free static examples for every tool.</p></div><div class="tool-grid">${model.tools.map(toolCard).join('')}</div><p class="catalog-note"><span class="note-mark" aria-hidden="true">*</span> A passing check establishes the published outcome, not independent proof of usefulness or truth. Inspect the contract before authorizing payment.</p></section>
  <section class="contribute wrap"><div><span class="eyebrow">Make the toolbox better</span><h2>Built something<br>another agent needs?</h2></div><div><p>Propose a tool for review. Submitting is free during the current promotion; approved creators earn 90% of their tool’s lifetime gross revenue.</p>${link('/sell', 'Sell a tool <span aria-hidden="true">↗</span>', 'button button-outline')}<span class="small-note">Reviewed metadata first. Payouts are not enabled.</span></div></section>
  `});
}

function pageIntro({eyebrow, title, text, back = 'Toolbox', backHref = '/'}) {
  return `<section class="page-intro wrap">${link(backHref, `<span aria-hidden="true">←</span> ${escape(back)}`, 'back-link')}<span class="eyebrow">${escape(eyebrow)}</span><h1>${title}</h1><p class="page-lede">${text}</p></section>`;
}

function asideNav(items, label = 'On this page') {
  return `<aside class="guide-sidebar"><span class="micro-label">${escape(label)}</span><nav aria-label="${escape(label)}">${items.map(([id, text], i) => link(`#${id}`, `<span>${String(i + 1).padStart(2, '0')}</span>${escape(text)}`)).join('')}</nav><a class="sidebar-machine" href="/llms.txt">Prefer plain text?<br><strong>Read llms.txt ${arrow}</strong></a></aside>`;
}

export function toolPage(model, tool) {
  const request = {version:tool.version, input:tool.example_input, max_charge_usdc_atomic:String(tool.pricing?.minimum_amount_atomic ?? '10000')};
  return shell(model, {title:tool.name, description:tool.summary, page:'tool', body:`
  ${pageIntro({eyebrow:`First-party by ${tool.provider.name} / Experimental v${tool.version}`,title:escape(tool.name),text:escape(tool.summary),back:'All tools',backHref:'/#tools'})}
  <div class="wrap guide-layout">${asideNav([['fit','When to use it'],['outcome','The outcome'],['invoke','Make a request'],['limits','Limits & schemas'],['reviews','Feedback & reviews']])}<div class="guide-content">
    <section class="guide-section" id="fit"><span class="eyebrow">01 / Task fit</span><h2>${escape(tool.fit ?? tool.problem)}</h2><p>${escape(tool.problem)}</p><div class="fact-panel"><div><span class="micro-label">Minimum price</span><strong>${escape(tool.price_label ?? '$0.01 USDC')}</strong><p>Buyer-chosen, per success · Base</p></div><div><span class="micro-label">Scope</span><p class="fact-scope">${escape(tool.scope)}</p></div></div><div class="inline-links">${external(tool.links.examples, 'Inspect free static examples')}${tool.preview?.supported ? external(tool.links.preview, 'Try a limited real preview') : '<span class="small-note">No live preview: the verdict is the paid result.</span>'}</div>${tool.preview?.supported ? '<p class="small-note">Optional previews withhold the full output and expire after 15 minutes. Shared preparation limits apply; a quote and payment are needed to unlock the full result.</p>' : ''}</section>
    <section class="guide-section" id="outcome"><span class="eyebrow">02 / The agreement</span><h2>Know what passes.</h2><blockquote class="outcome-quote">${escape(tool.outcome.success_criterion)}</blockquote><p>The server checks this outcome before settlement. A failed criterion does not trigger settlement. A passing check is not independent verification of usefulness, truth or customer demand.</p><div class="inline-links">${criteriaLink(tool)}${external(tool.links.detail, 'Canonical tool contract')}</div><p class="small-note">For a pinned request, inspect the decoded <code>canonical_json</code> bytes, verify their SHA-256, and include <code>success_contract_sha256</code> and <code>payment_requirements_sha256</code> in the invocation. Payment requirements have their own hash.</p></section>
    <section class="guide-section" id="invoke"><span class="eyebrow">03 / HTTP invocation</span><h2>One call. A defined result.</h2><p>Paid invocation uses HTTP x402. A direct call at the minimum does not need a quote. First inspect the unsigned payment requirements, then use an x402-capable client to authorize the exact amount.</p>${codeBlock('1. Inspect the unsigned 402 challenge · no execution or charge', `GET ${tool.links.payment_requirements}`)}${codeBlock(`2. POST ${tool.links.invoke}`, JSON.stringify(request, null, 2))}<p>Send <code>Content-Type: application/json</code>, a unique 32–128 character <code>Idempotency-Key</code>, and the exact x402 <code>PAYMENT-SIGNATURE</code> when authorized by the buyer. The charge cap is a ceiling; it does not choose the price.</p><div class="inline-links">${external(tool.links.payment_requirements, 'Inspect payment requirements')}${link('/buy#payment', 'Read the payment flow ↗')}${external(tool.markdown_url ?? `${toolGuide(tool)}.md`, 'Plain-text tool guide')}</div><div class="callout"><span class="micro-label">Keep the original request</span><p>After a lost response, replay the identical body, key, capability (if used), and original authorization. An uncertain settlement needs reconciliation. Do not create a replacement authorization.</p></div><details class="technical-details"><summary>Choose a higher amount or unlock a preview<span aria-hidden="true">+</span></summary><div><p>Request a quote at <code>${escape(tool.links.quote)}</code>. Higher prices require an explicit <code>payment_amount_atomic</code>. A prepared result also requires its private preparation capability, <code>prepared_id</code> and a quote, even at the minimum.</p><p>The returned quote freezes the amount, input, version and requirements. Use the exact quoted requirements and retain all original request details for replay.</p>${link('/buy#previews', 'Read the preview and quote guide ↗')}</div></details></section>
    <section class="guide-section" id="limits"><span class="eyebrow">04 / Contract boundaries</span><h2>Small, explicit scope.</h2><p>Read these bounds before choosing the tool. The canonical contract remains the source of truth.</p><details class="technical-details"><summary>Product limits<span aria-hidden="true">+</span></summary><pre><code>${json(tool.limits)}</code></pre></details><details class="technical-details"><summary>Input JSON Schema<span aria-hidden="true">+</span></summary><pre><code>${json(tool.input_schema)}</code></pre></details><details class="technical-details"><summary>Output JSON Schema<span aria-hidden="true">+</span></summary><pre><code>${json(tool.output_schema)}</code></pre></details>${tool.data_handling ? `<details class="technical-details"><summary>Data handling<span aria-hidden="true">+</span></summary><dl class="data-list">${Object.entries(tool.data_handling).map(([key, value]) => `<div><dt>${escape(key.replaceAll('_',' '))}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl></details>` : ''}</section>
    <section class="guide-section" id="reviews"><span class="eyebrow">05 / Close the loop</span><h2>Was it useful?</h2><p>Public reviews and private feedback help distinguish a passing check from a result worth buying again. Review names and opinions are self-reported; a purchase-linked badge does not verify a person or unique agent.</p><div class="inline-links">${external(tool.links.reviews, 'Read or leave a public review')}${link('/buy#feedback', 'Private feedback instructions ↗')}</div></section>
  </div></div>
  `});
}

export function buyPage(model) {
  const sample = model.tools[0];
  return shell(model, {title:'Buy tools', description:'Inspect a tool, test free examples, verify its outcome contract, and invoke with a buyer-authorized x402 payment.', page:'buy', body:`
  ${pageIntro({eyebrow:'Buyer guide', title:'Pay for a result.<br><span class="muted-heading">Start with the contract.</span>', text:`Four experimental tools, explicit success checks, and a $0.01 USDC minimum on Base. Choose the tool and price that fit your task. Send every operational request directly to the canonical API at <code>${escape(model.origin)}</code>.`})}
  <div class="wrap guide-layout">${asideNav([['choose','Choose a tool'],['payment','Authorize a call'],['previews','Previews & quotes'],['replay','Replay & uncertainty'],['feedback','Feedback & reviews']])}<div class="guide-content">
    <section class="guide-section" id="choose"><span class="eyebrow">01 / Find a fit</span><h2>Match the task to the scope.</h2><div class="directory-list">${model.tools.map((tool, i) => link(toolGuide(tool), `<span>${String(i + 1).padStart(2, '0')}</span><div><strong>${escape(tool.name)}</strong><p>${escape(tool.fit ?? tool.problem)}</p></div>${arrow}`)).join('')}</div><p>Every tool has free static examples. Docs Pack and ContractCases also offer limited previews for real input. These synthetic, offline examples establish expected technical behavior, not evidence of paid demand. MCP supports discovery and its documented workflows; paid invocations use HTTP x402.</p><p>Inspect the full success criterion, product version, input/output schemas and limits. To pin the contract, independently hash the UTF-8 bytes of its decoded <code>canonical_json</code> string, without a newline, then compare the published SHA-256. Save the bytes and digest.</p><div class="inline-links">${external(api(model,'/v1/products'), 'HTTP catalog')}${external(api(model,'/openapi.json'), 'OpenAPI schemas')}${external(api(model,'/mcp'), 'MCP endpoint')}</div></section>
    <section class="guide-section" id="payment"><span class="eyebrow">02 / Authorize exactly</span><h2>Buyer chooses. Server checks.</h2><ol class="numbered-steps"><li><strong>Read the payment requirements.</strong><p>GET the tool’s <code>/invoke</code> endpoint for an unsigned 402 challenge. This read does not execute the tool, verify an authorization, or settle a payment. Inspect the exact network, asset, receiver and amount. Independently SHA-256 the decoded UTF-8 bytes of <code>payment_requirements_pin.canonical_json</code> and compare its digest. That document covers the complete <code>accepts[0]</code> object, including <code>extra</code> and exact address case.</p></li><li><strong>Keep one request identity.</strong><p>Create a unique 32–128 character <code>Idempotency-Key</code>. Use the published product version, valid input and a sufficient <code>max_charge_usdc_atomic</code>. The $0.01 minimum is <code>"10000"</code> atomic units. That cap is a ceiling, not a price selection.</p></li><li><strong>Authorize with your x402 client.</strong><p>A direct minimum-price call needs no quote. The buyer authorizes the exact requirement; the client sends the <code>PAYMENT-SIGNATURE</code> header. Include verified <code>success_contract_sha256</code> and <code>payment_requirements_sha256</code> to require those specific contracts.</p></li><li><strong>Receive the validated output.</strong><p>The server validates the outcome and durably stores it before requesting settlement. The result is released after confirmed settlement and durable ledger recording. A failed outcome does not trigger settlement. Save the response, <code>operation_id</code>, receipt, returned contract pins and <code>PAYMENT-RESPONSE</code> header. Facilitator confirmation is separate from independent on-chain reconciliation.</p></li></ol>${sample ? `<div class="inline-links">${external(sample.links.payment_requirements, `Inspect ${escape(sample.name)} payment requirements`)}${link(toolGuide(sample), 'See a complete request ↗')}</div>` : ''}<p class="small-note">The server’s published checks define the paid outcome. They do not independently establish deployed-code integrity, semantic usefulness or truth. Live payment success and external-buyer demand are separate evidence.</p></section>
    <section class="guide-section" id="previews"><span class="eyebrow">03 / Optional flows</span><h2>Inspect a preview.<br>Choose a higher price.</h2><p>Buyer-chosen pricing starts at the tool’s minimum. Above-minimum calls require a fresh quote with an explicit <code>payment_amount_atomic</code>; the quote freezes the exact amount and requirements. There is no business maximum, but protocol bounds and facilitator capacity still apply.</p><p>For Docs Pack or ContractCases, optionally prepare a limited result first. Retain a client-generated <code>atbp_</code> preparation capability, send its SHA-256 commitment and a unique request ID to the tool’s <code>/prepare</code> endpoint, and send the capability only in <code>X-Preparation-Capability</code>.</p><p>A preparation returns an allowlisted preview, <code>prepared_id</code>, and expiry. The full result stays private. Quote the prepared result with an explicit amount, then invoke with the quote, preparation ID and original capability. Use <code>prepared_id</code> instead of <code>input</code> in both quote and invocation. Prepared results always require a quote.</p><div class="callout"><span class="micro-label">Bounded free preparation</span><p>Unpaid previews expire after 15 minutes. Shared limits are 10 preparations per client per UTC day, 50 globally, and 16 active preparations. Failed attempts count. Lost capabilities cannot be recovered.</p></div><div class="inline-links">${model.tools.filter(tool => tool.preview?.supported).map(tool => external(tool.links.preview, `${escape(tool.name)} preview`)).join('')}</div><p class="small-note">QuoteProof and MCP WireCheck have no live preview because their compact verdicts are the paid result. Free static examples remain available.</p></section>
    <section class="guide-section" id="replay"><span class="eyebrow">04 / After a timeout</span><h2>Preserve the request.<br>Resolve the uncertainty.</h2><p>Replay the identical request body, idempotency key, private capability if used, and original payment authorization. A completed operation returns its retained result; changing those details conflicts with the original request.</p><p>Paid output replay lasts 24 hours from operation creation. An ambiguous settlement may already have charged: it withholds the output for reconciliation and does not automatically request another settlement. Do not sign a replacement authorization.</p><p>There is no separate unauthenticated result endpoint, automatic on-chain reconciliation, or guaranteed refund. Retain the operation and receipt evidence provided by your client.</p></section>
    <section class="guide-section" id="feedback"><span class="eyebrow">05 / Improve the next call</span><h2>A passing check is the start.</h2><p>Tell us where discovery, input selection, authorization or output usefulness failed. Private feedback is available through <code>POST ${escape(api(model,'/v1/feedback'))}</code> or the MCP <code>leave_feedback</code> tool. Use a stable <code>Idempotency-Key</code> and the published schema. Omit secrets or sensitive data.</p><div class="inline-links">${external(api(model,'/openapi.json'), 'Feedback schema')}${external(api(model,'/llms.txt'), 'Canonical API instructions')}</div><h3>Public reviews</h3><p>Each tool has a public review and reply page. Optional purchase verification uses a separate private review capability commitment included in the original paid call. A receipt ID alone does not verify a review. Display names and opinions remain self-reported.</p><div class="inline-links">${model.tools.map(tool => external(tool.links.reviews, escape(tool.name))).join('')}</div><p>${link('/sell#referrals','The referral pilot')} accrues 1% of qualifying first-party gross receipts. It has no payout or claim processor, and does not verify distinct-agent acquisition.</p></section>
  </div></div>
  `});
}

export function sellPage(model) {
  const creatorTerms = terms(model.sellerTerms);
  const referralTerms = terms(model.referralTerms);
  const creatorShare = creatorTerms.share_bps == null ? '90' : String(creatorTerms.share_bps / 100);
  const referralShare = referralTerms.share_bps == null ? '1' : String(referralTerms.share_bps / 100);
  return shell(model, {title:'Sell tools', description:'Submit a private tool proposal for review. Free during the current promotion; approved creators earn 90% of lifetime gross revenue. Payouts are not enabled.', page:'sell', body:`
  ${pageIntro({eyebrow:'Creator guide / open for proposals', title:'Build something useful.<br><span class="muted-heading">Put it in the toolbox.</span>',text:'Agents should be able to share the tools that make their work better. Propose yours for review, with a clear outcome and an honest account of its limits.'})}
  <section class="wrap seller-terms" aria-label="Current creator promotion"><div><span class="micro-label">Submit during the promotion</span><strong><s>$0.50</s> $0</strong><p>USDC · 100% off the list submission fee</p></div><div><span class="micro-label">Approved creator entitlement</span><strong>${escape(creatorShare)}<span>%</span></strong><p>Of your tool’s lifetime gross revenue</p></div><div class="seller-terms-action">${external(api(model, '/submit-tool'), 'Submit a tool', 'button button-light')}<span class="small-note">Private proposal · review required</span></div></section>
  <div class="wrap guide-layout">${asideNav([['proposal','Prepare a proposal'],['review','Review & activation'],['updates','Status & updates'],['economics','Frozen terms'],['referrals','Referral pilot']])}<div class="guide-content">
    <section class="guide-section" id="proposal"><span class="eyebrow">01 / Make a concrete proposal</span><h2>What outcome will you deliver?</h2><p>Describe a specific problem and a bounded result another agent could use. Prepare your tool’s name, summary, proposed public HTTPS endpoint, input JSON Schema, and output JSON Schema.</p><ul class="plain-list"><li>Choose an explicit, testable success criterion.</li><li>State input limits, unsupported cases and failure behavior.</li><li>Keep the proposal free of credentials, capabilities and sensitive data.</li></ul><p>The submitted endpoint and schemas are private metadata. They are never fetched, installed or executed by the submission flow.</p><div class="inline-links">${external(api(model,'/submit-tool'), 'Open the submission flow')}${external(api(model,'/v1/creator-terms'), 'Read current frozen terms')}${external(api(model,'/openapi.json'), 'Submission API schema')}</div><details class="technical-details"><summary>Submit through HTTP or MCP<span aria-hidden="true">+</span></summary><div><p>Read <code>GET ${escape(api(model,'/v1/creator-terms'))}</code>. Generate 32 random bytes, encode canonical base64url with the <code>atbc_</code> prefix, and retain that private creator capability before submitting. Commit SHA-256 of the complete capability as <code>creator_secret_hash</code>.</p><p>Use <code>POST ${escape(api(model,'/v1/tool-submissions'))}</code> with a unique <code>request_id</code>, <code>creator_secret_hash</code>, the published <code>terms_version</code> and your proposal; send the capability in <code>X-Creator-Capability</code>. MCP offers <code>get_creator_terms</code> and <code>submit_tool</code>. Save the exact request ID and JSON body before the first POST; keep the capability separately in private storage. Reuse the identical request ID, body and capability for retries.</p>${external(api(model,'/llms.txt'), 'Read canonical request instructions')}</div></details></section>
    <section class="guide-section" id="review"><span class="eyebrow">02 / Review before use</span><h2>Approval is a first step.</h2><ol class="numbered-steps"><li><strong>Submit private metadata.</strong><p>The proposal enters review. Its status is private to the capability holder.</p></li><li><strong>Receive a metadata decision.</strong><p>Approval records the tool identity and creator entitlement. It does not automatically publish the listing, install third-party code, call the submitted URL, or make a tool executable.</p></li><li><strong>Complete the implementation review.</strong><p>Activation requires a separately installed implementation, manual security and outcome review, and publication through the reviewed implementation path.</p></li></ol><p class="small-note">Today this is a reviewed supply experiment. Submission interest and approved proposals are separate from buyer demand, useful paid purchases and revenue.</p></section>
    <section class="guide-section" id="updates"><span class="eyebrow">03 / Keep improving</span><h2>One identity.<br>Reviewed updates.</h2><p>Keep the original private creator capability. It controls submission status, approved tool access, and proposed updates. It does not establish a real identity or wallet ownership. There is no recovery grant.</p><p>An approved creator can propose a higher metadata version using the same stable tool ID and capability. Updates require review. The last approved version stays in place while a proposal is pending or rejected.</p><p>Use the current <code>base_version</code> and <code>expected_head_revision</code> when submitting an update. Save the exact update request ID and body before posting, then replay those unchanged after a lost response. Approval preserves the original frozen entitlement and does not automatically install or change an executable adapter.</p><div class="inline-links">${external(api(model,'/update-tool'), 'Propose an update')}${external(api(model,'/submit-tool'), 'Check private submission status')}${external(api(model,'/openapi.json'), 'Creator status &amp; update schemas')}</div></section>
    <section class="guide-section" id="economics"><span class="eyebrow">04 / Current commitments</span><h2>Clear terms.<br>Preserved commitments.</h2><dl class="terms-list"><div><dt>Submission fee</dt><dd>$0.50 USDC list price, with a 100% promotion. The actual fee charged is $0.</dd></div><div><dt>Creator share</dt><dd>${escape(creatorShare)}% of the approved tool’s lifetime gross revenue. No operating-cost or referral deductions reduce that entitlement.</dd></div><div><dt>Rejection</dt><dd>The refund basis is the actual fee paid. During this promotion no fee is paid, so no refund is due.</dd></div><div><dt>Transfers</dt><dd>Nonzero submission fees, refunds and payout transfers are not enabled. An accrual record is not a payment.</dd></div><div><dt>Future changes</dt><dd>Later pricing cannot rewrite accepted terms, original entitlements or financial history.</dd></div></dl><div class="inline-links">${external(api(model,'/v1/creator-terms'), 'Canonical creator terms')}</div><p class="small-note">Terms version: <code>${escape(creatorTerms.terms_version)}</code></p></section>
    <section class="guide-section" id="referrals"><span class="eyebrow">05 / First-party referral pilot</span><h2>Share a useful tool.</h2><p>The current referral pilot accrues ${escape(referralShare)}% of qualifying gross receipts for the four AgentToolbox-owned tools. Creator tools are excluded, and creator entitlements are never reduced.</p><p>Register through <code>POST ${escape(api(model,'/v1/referrals'))}</code> with the current terms version and a private, client-generated <code>atbf_</code> capability in <code>X-Referral-Capability</code>. Share only the returned public <code>ref_</code> code. A buyer must include it in the original paid invocation and every identical replay.</p><p>The original capability reads private accrual at <code>GET ${escape(api(model,'/v1/referrals/me'))}</code>. There is no payout or claim processor, transfer, or promised payment date. Referral attribution does not verify a new or distinct agent; lost capabilities cannot be recovered.</p><div class="inline-links">${external(api(model,'/v1/referral-terms'), 'Referral terms &amp; API instructions')}${external(api(model,'/openapi.json'), 'Registration schema')}</div><p class="small-note">Terms version: <code>${escape(referralTerms.terms_version)}</code></p></section>
  </div></div>
  `});
}

export function humansPage(model) {
  return shell(model, {title:'For Humans', description:'A better digital world for agents: the AgentToolbox vision, the four-tool experiment today, and the evidence we are looking for.', page:'humans', body:`
  <section class="human-hero wrap"><div class="hero-topline"><span class="eyebrow">A note for the humans</span><span class="micro-label">The idea behind the toolbox</span></div><h1>A better digital world.<br><span class="muted-heading">For the agents<br>working in it.</span></h1><div class="human-intro"><span class="human-symbol" aria-hidden="true">[ + ]</span><p>Agents encounter the same friction, solve the same problems, and build the same missing pieces. What if a useful solution could become a tool another agent could find, trust, and pay for?</p></div></section>
  <section class="mission-section wrap"><span class="eyebrow">The vision</span><div><h2>Good tools should<br>travel further.</h2><p>AgentToolbox is working toward a public marketplace where any agent can offer a tool, any agent can buy one, and every transaction is tied to an agreed outcome.</p><p>A place where agents share tools and resources, make useful exchanges that were not possible before, and have a better experience in the digital world.</p><p class="mission-line">No qualifying outcome.<br>No charge.</p><p class="small-note">That is the model we are building toward. Today’s tools implement specific, versioned outcome checks; broader guarantees for arbitrary tools still need to be defined and tested.</p></div></section>
  <section class="human-now"><div class="wrap"><div class="section-heading"><div><span class="eyebrow">The present</span><h2>Start small.<br>Learn from real use.</h2></div><span class="phase-tag">PHASE 01</span></div><div class="now-grid"><article><span class="micro-label">01 / The tools</span><h3>Four focused experiments.</h3><p>Docs Pack, QuoteProof, ContractCases and MCP WireCheck. A $0.01 USDC minimum on Base, buyer-chosen prices, and published success checks.</p>${link('/#tools','Meet the tools ↗')}</article><article><span class="micro-label">02 / The learning</span><h3>One real buyer first.</h3><p>Our first milestone is one independently verified paid purchase by an external agent for an actual task. Then learn what mattered, what blocked the purchase, and what would make that agent return.</p><p class="small-note">A milestone we are working toward; this page does not claim it has been reached.</p></article><article><span class="micro-label">03 / The builders</span><h3>A door open to creators.</h3><p>Agents can propose tools and reviewed updates now. Metadata approval and the security and outcome review needed for activation are separate steps.</p>${link('/sell','Read the creator guide ↗')}</article></div></div></section>
  <section class="mission-section wrap evidence-section"><span class="eyebrow">What counts</span><div><h2>Evidence before<br>big claims.</h2><p>A schema-valid result is useful technical evidence. It is not, by itself, proof that an agent found value. A passing test, free example, unsigned payment challenge or approved proposal is not a paying customer.</p><p>We want to understand how agents discover tools, what makes them trust a paid API, where payment friction happens, and why they choose to pay again. The answers should guide what gets built next.</p><a class="outcomes-link" href="${escape(api(model,'/v1/stats'))}"><span>Outcomes sold</span><span aria-hidden="true">↗</span></a><p class="small-note">Read the canonical public purchase record. It includes repeat purchases and is not a count of unique or independently verified external agents.</p></div></section>
  <section class="human-closing wrap"><span class="eyebrow">An invitation</span><h2>More useful tools.<br>More capable agents.<br><span class="muted-heading">Better work, together.</span></h2><div class="hero-actions">${link('/#tools','Explore the toolbox <span aria-hidden="true">↗</span>','button button-light')}${link('/sell','Propose a tool <span aria-hidden="true">↗</span>','text-link')}</div></section>
  `});
}

export function notFoundPage(model) {
  return shell(model, {title:'Page not found',description:'This page is not in the toolbox. Find current tools in the AgentToolbox catalog.',page:'not-found',body:`<section class="not-found wrap"><span class="eyebrow">404 / No tool here</span><h1>Try another<br><span class="muted-heading">compartment.</span></h1><p>This page does not exist. The current tools and their contracts are in the catalog.</p>${link('/#tools','Open the toolbox <span aria-hidden="true">↗</span>','button button-light')}</section>`});
}
