import {header,headerStylesheet} from './header.js';
import {agentStylesheet} from './pages.js';
import {formsStylesheet} from './workflow-theme.js';
import {walletProofSection} from './wallet-proof-section.js';
import {creatorEarningsSection} from './creator-earnings-section.js';
import {payoutRequestSection} from './payout-request-section.js';
import {REFERRAL_TERMS} from '../../platform/src/referrals.js';

export const referralAccountScript='<script type="module" src="/referral-account.js?v=1"></script>';
const escape=value=>String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');

export function referralPage({payoutRequestsEnabled=false}={}){
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><meta name="description" content="Register a first-party referral code, manage its Base payout destination, and read private earnings."><title>AgentToolbox</title><link rel="icon" href="/agenttoolbox-icon.png" type="image/png">${headerStylesheet}${agentStylesheet}${formsStylesheet}${referralAccountScript}</head><body><a class="skip-link" href="#main">Skip to content</a>${header('agents')}<main id="main" class="document workflow-document" data-referral-page><section class="workflow" data-referral-account data-terms-version="${escape(REFERRAL_TERMS.terms_version)}"><a href="/buy#after-the-result">← Referral guide</a><h1>Referral account</h1>
<p>Earn 1% of qualifying gross sales referred to DocsPack, QuoteProof, ContractCases, and MCPWireCheck. Creator tools are excluded. Include your public referral code in the original paid invocation; attribution cannot be added afterward.</p>
<p class="footnote">Your private capability controls this account, its destination, and its earnings. Keep it privately: there is no recovery grant. It is an account credential, never a wallet private key or seed phrase.</p>
<label for="referral-capability">Private referral capability<input id="referral-capability" data-capability data-referral-account-control type="password" autocomplete="off" spellcheck="false" maxlength="48" required pattern="atbf_[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]"></label>
<div class="workflow-actions"><button type="button" data-generate-referral data-referral-account-control data-referral-enhanced hidden>Generate new capability</button><button type="button" data-reveal-referral data-referral-account-control data-referral-enhanced hidden>Reveal capability</button><button type="button" data-copy-referral data-referral-account-control data-referral-enhanced hidden>Copy private capability</button><button type="button" data-read-referral data-referral-account-control data-referral-enhanced hidden>Read account</button></div>
<p class="footnote">Returning referrers: paste the capability you already saved and read your account. New referrers: generate one locally and save it before registering. The same capability is used throughout this page, only in private request headers. It is never saved in browser storage or exported with retry requests.</p>
<form data-referral-registration method="post" action="/v1/referrals" autocomplete="off">
<label class="public-consent"><input type="checkbox" data-referral-capability-saved data-referral-account-control> I saved this private capability separately and understand it cannot be recovered.</label>
<label class="public-consent"><input type="checkbox" data-referral-terms-accepted data-referral-account-control> I accept the <a href="/v1/referral-terms">published first-party referral terms</a> (${escape(REFERRAL_TERMS.terms_version)}).</label>
<div class="workflow-actions"><button type="button" data-prepare-registration data-referral-account-control data-referral-enhanced hidden>Prepare registration</button></div>
<section data-registration-prepared hidden><h2>Review and save registration</h2><p class="footnote">Preparation and import send nothing. Save this JSON and keep the capability separately. Retrying with the original capability returns the same referral account.</p><label for="referral-registration-envelope">Exact registration request<textarea id="referral-registration-envelope" data-registration-envelope rows="10" readonly spellcheck="false" autocomplete="off"></textarea></label><div class="workflow-actions"><button type="button" data-copy-registration data-referral-account-control>Copy request</button><button type="button" data-export-registration data-referral-account-control>Download request JSON</button></div><label class="public-consent"><input type="checkbox" data-registration-saved data-referral-account-control> I saved this exact request with my capability kept separately.</label><div class="workflow-actions"><button type="submit" data-referral-account-control>Register with this exact request</button><button type="button" data-new-registration data-referral-account-control>Clear resolved registration request</button></div></section>
<details class="retry-request"><summary>Restore registration request</summary><label for="referral-registration-import">Saved registration request JSON<textarea id="referral-registration-import" data-registration-import data-referral-account-control rows="7" maxlength="4096" autocomplete="off" spellcheck="false"></textarea></label><label for="referral-registration-file">Or choose a saved JSON file<input id="referral-registration-file" data-registration-file data-referral-account-control type="file" accept="application/json,.json"></label><button type="button" data-restore-registration data-referral-account-control data-referral-enhanced hidden>Restore registration</button></details>
<p data-account-status role="status" aria-live="polite"></p><pre class="workflow-result" data-account-result hidden></pre>
<noscript>Use the JSON API in <a href="/openapi.json">OpenAPI</a> to register and read your private account. This page needs JavaScript to send capabilities in headers; it does not submit them through native forms.</noscript></form></section>
<section class="workflow" id="referral-wallet"><h2>1. Save a Base destination</h2><p>Use the same referral capability above after registration. An address is UNVERIFIED until its separate ownership proof is verified. Owner approval is separate. Saving an address does not initiate a payout.</p>
<form data-referral-wallet method="post" action="/v1/referrals/me/payout-wallet" autocomplete="off"><div class="workflow-actions"><button type="button" data-read-status hidden>Read current wallet status</button></div><pre class="workflow-result" data-wallet-current hidden></pre><label for="referral-wallet-revision">Current revision<input id="referral-wallet-revision" data-current-revision readonly placeholder="Read current status first"></label><label for="referral-wallet-address">Public Base wallet address<input id="referral-wallet-address" data-wallet-address type="text" autocomplete="off" spellcheck="false" maxlength="42" required pattern="0x[0-9a-fA-F]{40}" placeholder="0x…"></label><p class="footnote">Network: Base (chain 8453). Never enter a wallet private key or seed phrase. Proof currently supports externally owned accounts (EOA); smart-contract wallets (ERC-1271) are unsupported.</p><div class="workflow-actions"><button type="button" data-prepare-wallet hidden>Prepare destination claim</button></div>
<section data-wallet-prepared hidden><h3>Review and save the exact claim</h3><p class="footnote">Preparation and import send nothing. Save this JSON before sending. After a timeout or reload, restore it and retry unchanged with the original referral capability.</p><label for="referral-wallet-envelope">Prepared retry request<textarea id="referral-wallet-envelope" data-wallet-envelope rows="14" readonly spellcheck="false" autocomplete="off"></textarea></label><div class="workflow-actions"><button type="button" data-copy-wallet>Copy request</button><button type="button" data-export-wallet>Download request JSON</button></div><label class="public-consent"><input data-wallet-saved type="checkbox"> I saved this exact request and kept my capability separately.</label><div class="workflow-actions"><button type="submit" data-send-wallet>Send this exact claim</button><button type="button" data-new-wallet>Start a different claim</button></div></section>
<details class="retry-request"><summary>Restore a destination claim</summary><label for="referral-wallet-import">Saved retry request JSON<textarea id="referral-wallet-import" data-wallet-import rows="7" maxlength="4096" spellcheck="false" autocomplete="off"></textarea></label><label for="referral-wallet-file">Or choose a saved JSON file<input id="referral-wallet-file" data-wallet-file type="file" accept="application/json,.json"></label><button type="button" data-restore-wallet hidden>Restore exact request</button></details><span role="status" aria-live="polite"></span><pre class="workflow-result" data-wallet-result hidden></pre><noscript>Use the capability-protected referral wallet API described in <a href="/openapi.json">OpenAPI</a>. No credential is sent by this native form.</noscript></form></section>
${walletProofSection({kind:'referral'})}${creatorEarningsSection({kind:'referral'})}${payoutRequestSection({kind:'referral',payoutRequestsEnabled})}
</main><footer class="document-footer workflow-footer"><nav aria-label="Toolbox links"><a href="/tools">Browse tools</a><a href="/sell">Sell tools</a><a href="/buy#after-the-result">Referral guide</a><a href="/llms.txt">llms.txt</a><a href="/openapi.json">OpenAPI</a></nav><p>Built for agents, by agents.</p></footer></body></html>`;
}
